JM_dlcGear = [
  ["CBRN_Expansion_Gendarmerie", "contact"],
  ["CBRN_Expansion_Yellow", "contact"],
  ["CBRN_Expansion_Olive", "contact"],
  ["CBRN_Expansion_NoDecals_yellow", "contact"],
  ["CBRN_Expansion_NoDecals_Cyan", "contact"],
  ["CBRN_Expansion_NoDecals_BlueGreenish", "contact"],
  ["CBRN_Expansion_NoDecals_Orange", "contact"],
  ["CBRN_Expansion_M81", "contact"],
  ["CBRN_Expansion_TCD", "contact"],
  ["arifle_Katiba_F", "reaction forces"],
  ["arifle_Katiba_C_F", "reaction forces"],
  ["arifle_Katiba_GL_F", "reaction forces"],
  ["EF_LPNVG", "expeditionary forces"],
  ["EF_LPNVG_Tan", "expeditionary forces"],
  ["EF_LPNVG_T", "expeditionary forces"],
  ["EF_LPNVG_T_Tan", "expeditionary forces"],
  ["EF_acc_pointer_IR_coy", "expeditionary forces"],
  ["ef_snds_mxar", "expeditionary forces"],
  ["ef_snds_mxar_sand", "expeditionary forces"],
  ["ef_snds_mxar_coy", "expeditionary forces"],
  ["ef_snds_mxar_khk", "expeditionary forces"],
  ["ef_optic_mbs", "expeditionary forces"],
  ["ef_optic_mbs_remote", "expeditionary forces"],
  ["ef_optic_mbs_coy", "expeditionary forces"],
  ["ef_optic_mbs_remote_coy", "expeditionary forces"],
  ["ef_optic_mbs_khk", "expeditionary forces"],
  ["ef_optic_mbs_remote_khk", "expeditionary forces"],
  ["ef_optic_mbs_sand", "expeditionary forces"],
  ["ef_optic_mbs_remote_sand", "expeditionary forces"],
  ["ef_optic_microsight", "expeditionary forces"],
  ["ef_optic_microsight_pistol", "expeditionary forces"],
  ["ef_optic_microsight_coy", "expeditionary forces"],
  ["ef_optic_microsight_pistol_coy", "expeditionary forces"],
  ["ef_optic_microsight_khk", "expeditionary forces"],
  ["ef_optic_microsight_pistol_khk", "expeditionary forces"],
  ["ef_optic_microsight_sand", "expeditionary forces"],
  ["ef_optic_microsight_pistol_sand", "expeditionary forces"],
  ["ef_optic_Holosight_coy", "expeditionary forces"],
  ["ef_optic_Holosight_smg_coy", "expeditionary forces"],
  ["ef_arifle_mxar", "expeditionary forces"],
  ["ef_arifle_mxar_gl", "expeditionary forces"],
  ["ef_arifle_mxar_black", "expeditionary forces"],
  ["ef_arifle_mxar_gl_black", "expeditionary forces"],
  ["ef_arifle_mxar_khk", "expeditionary forces"],
  ["ef_arifle_mxar_gl_khk", "expeditionary forces"],
  ["ef_arifle_mxar_coy", "expeditionary forces"],
  ["ef_arifle_mxar_gl_coy", "expeditionary forces"],
  ["U_C_Driver_1", "karts"],
  ["U_C_Driver_2", "karts"],
  ["U_C_Driver_3", "karts"],
  ["U_C_Driver_4", "karts"],
  ["U_C_Driver_1_black", "karts"],
  ["U_C_Driver_1_blue", "karts"],
  ["U_C_Driver_1_green", "karts"],
  ["U_C_Driver_1_red", "karts"],
  ["U_C_Driver_1_white", "karts"],
  ["U_C_Driver_1_yellow", "karts"],
  ["U_C_Driver_1_orange", "karts"],
  ["U_B_FullGhillie_lsh", "marksmen"],
  ["U_B_FullGhillie_sard", "marksmen"],
  ["U_B_FullGhillie_ard", "marksmen"],
  ["U_O_FullGhillie_lsh", "marksmen"],
  ["U_O_FullGhillie_sard", "marksmen"],
  ["U_O_FullGhillie_ard", "marksmen"],
  ["U_I_FullGhillie_lsh", "marksmen"],
  ["U_I_FullGhillie_sard", "marksmen"],
  ["U_I_FullGhillie_ard", "marksmen"],
  ["V_HarnessOSpec_brn", "western sahara"],
  ["V_HarnessOSpec_gry", "western sahara"],
  ["H_RacingHelmet_1_F", "karts"],
  ["H_RacingHelmet_2_F", "karts"],
  ["H_RacingHelmet_3_F", "karts"],
  ["H_RacingHelmet_4_F", "karts"],
  ["H_RacingHelmet_1_black_F", "karts"],
  ["H_RacingHelmet_1_blue_F", "karts"],
  ["H_RacingHelmet_1_green_F", "karts"],
  ["H_RacingHelmet_1_red_F", "karts"],
  ["H_RacingHelmet_1_white_F", "karts"],
  ["H_RacingHelmet_1_yellow_F", "karts"],
  ["H_RacingHelmet_1_orange_F", "karts"],
  ["EF_U_B_MarineCombatUniform_Des_1", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Des_2", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Des_3", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Des_4", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Des_5", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Des_6", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Wdl_1", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Wdl_2", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Wdl_3", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Wdl_4", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Wdl_5", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Wdl_6", "expeditionary forces"],
  ["EF_U_B_CrewCoveralls_Navy", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Diver_Des", "expeditionary forces"],
  ["EF_U_B_MarineCombatUniform_Diver_Wdl", "expeditionary forces"],
  ["EF_V_AAV_Coy", "expeditionary forces"],
  ["EF_V_AAV_Rifleman_Coy", "expeditionary forces"],
  ["EF_V_AAV_Sailor_Coy", "expeditionary forces"],
  ["EF_V_AAV_Scout_Coy", "expeditionary forces"],
  ["EF_V_AAV_Support_Coy", "expeditionary forces"],
  ["EF_V_AAV_TL_Coy", "expeditionary forces"],
  ["EF_V_AAV_Diver_Coy", "expeditionary forces"],
  ["EF_V_AAV_Olive", "expeditionary forces"],
  ["EF_V_AAV_Rifleman_Olive", "expeditionary forces"],
  ["EF_V_AAV_Sailor_Olive", "expeditionary forces"],
  ["EF_V_AAV_Scout_Olive", "expeditionary forces"],
  ["EF_V_AAV_Support_Olive", "expeditionary forces"],
  ["EF_V_AAV_TL_Olive", "expeditionary forces"],
  ["EF_V_AAV_Diver_Olive", "expeditionary forces"],
  ["EF_V_AAV_Black", "expeditionary forces"],
  ["EF_V_AAV_Rifleman_Black", "expeditionary forces"],
  ["EF_V_AAV_Sailor_Black", "expeditionary forces"],
  ["EF_V_AAV_Scout_Black", "expeditionary forces"],
  ["EF_V_AAV_Support_Black", "expeditionary forces"],
  ["EF_V_AAV_TL_Black", "expeditionary forces"],
  ["EF_V_AAV_Diver_Black", "expeditionary forces"],
  ["EF_V_CCR_Rifleman_Coy", "expeditionary forces"],
  ["EF_V_CCR_TL_Coy", "expeditionary forces"],
  ["EF_V_CCR_Scout_Coy", "expeditionary forces"],
  ["EF_V_CCR_Support_Coy", "expeditionary forces"],
  ["EF_V_CCR_Rifleman_Olive", "expeditionary forces"],
  ["EF_V_CCR_TL_Olive", "expeditionary forces"],
  ["EF_V_CCR_Scout_Olive", "expeditionary forces"],
  ["EF_V_CCR_Support_Olive", "expeditionary forces"],
  ["EF_V_CCR_Rifleman_Black", "expeditionary forces"],
  ["EF_V_CCR_TL_Black", "expeditionary forces"],
  ["EF_V_CCR_Scout_Black", "expeditionary forces"],
  ["EF_V_CCR_Support_Black", "expeditionary forces"],
  ["EF_H_MCH", "expeditionary forces"],
  ["EF_H_MCH_Basic", "expeditionary forces"],
  ["EF_H_MCH_BasicNet_Des", "expeditionary forces"],
  ["EF_H_MCH_BasicNet_Wdl", "expeditionary forces"],
  ["EF_H_MCH_BasicNet_Coy", "expeditionary forces"],
  ["EF_H_MCH_BasicNet_Olive", "expeditionary forces"],
  ["EF_H_MCH_BasicNet_Black", "expeditionary forces"],
  ["EF_H_MCH_FullCamo_Des", "expeditionary forces"],
  ["EF_H_MCH_FullCamo_Wdl", "expeditionary forces"],
  ["EF_H_MCH_FullCamo_Coy", "expeditionary forces"],
  ["EF_H_MCH_FullCamo_Olive", "expeditionary forces"],
  ["EF_H_MCH_FullCamo_Black", "expeditionary forces"],
  ["EF_H_MCH_Full", "expeditionary forces"],
  ["EF_H_Protecta", "expeditionary forces"],
  ["EF_H_UtilityCap_Wdl", "expeditionary forces"],
  ["EF_H_UtilityCap_Des", "expeditionary forces"],
  ["U_BG_leader_RF", "reaction forces"],
  ["U_BG_Guerrilla_RF", "reaction forces"],
  ["U_C_PilotJacket_black_RF", "reaction forces"],
  ["U_C_PilotJacket_brown_RF", "reaction forces"],
  ["U_C_PilotJacket_lbrown_RF", "reaction forces"],
  ["U_C_PilotJacket_open_black_RF", "reaction forces"],
  ["U_C_PilotJacket_open_brown_RF", "reaction forces"],
  ["U_C_PilotJacket_open_lbrown_RF", "reaction forces"],
  ["U_C_FirefighterFatigues_RF", "reaction forces"],
  ["U_C_FirefighterFatigues_RolledUp_RF", "reaction forces"],
  ["U_C_HeliPilotCoveralls_Rescue_RF", "reaction forces"],
  ["U_C_HeliPilotCoveralls_Black_RF", "reaction forces"],
  ["U_C_HeliPilotCoveralls_Yellow_RF", "reaction forces"],
  ["U_C_HeliPilotCoveralls_Blue_RF", "reaction forces"],
  ["U_C_HeliPilotCoveralls_Green_RF", "reaction forces"],
  ["V_TacVest_rig_khk_RF", "reaction forces"],
  ["V_TacVest_rig_blk_RF", "reaction forces"],
  ["V_TacVest_rig_oli_RF", "reaction forces"],
  ["V_TacVest_gen_holster_RF", "reaction forces"],
  ["V_PlateCarrierLite_black_noFlag_RF", "reaction forces"],
  ["lxWS_H_turban_01_black", "western sahara"],
  ["lxWS_H_turban_01_blue", "western sahara"],
  ["lxWS_H_turban_01_blue_una", "western sahara"],
  ["lxWS_H_turban_01_gray", "western sahara"],
  ["lxWS_H_turban_01_green", "western sahara"],
  ["lxWS_H_turban_01_red", "western sahara"],
  ["lxWS_H_turban_01_sand", "western sahara"],
  ["lxWS_H_turban_01_yellow", "western sahara"],
  ["lxWS_H_turban_02_black", "western sahara"],
  ["lxWS_H_turban_02_blue", "western sahara"],
  ["lxWS_H_turban_02_blue_una", "western sahara"],
  ["lxWS_H_turban_02_gray", "western sahara"],
  ["lxWS_H_turban_02_green", "western sahara"],
  ["lxWS_H_turban_02_green_pattern", "western sahara"],
  ["lxWS_H_turban_02_sand", "western sahara"],
  ["lxWS_H_turban_02_yellow", "western sahara"],
  ["lxWS_H_turban_02_orange", "western sahara"],
  ["lxWS_H_turban_02_red", "western sahara"],
  ["lxWS_H_turban_03_black", "western sahara"],
  ["lxWS_H_turban_03_blue", "western sahara"],
  ["lxWS_H_turban_03_blue_una", "western sahara"],
  ["lxWS_H_turban_03_gray", "western sahara"],
  ["lxWS_H_turban_03_green", "western sahara"],
  ["lxWS_H_turban_03_green_pattern", "western sahara"],
  ["lxWS_H_turban_03_sand", "western sahara"],
  ["lxWS_H_turban_03_yellow", "western sahara"],
  ["lxWS_H_turban_03_orange", "western sahara"],
  ["lxWS_H_turban_03_red", "western sahara"],
  ["lxWS_H_turban_04_black", "western sahara"],
  ["lxWS_H_turban_04_gray", "western sahara"],
  ["lxWS_H_turban_04_green", "western sahara"],
  ["lxWS_H_turban_04_sand", "western sahara"],
  ["lxWS_H_turban_04_blue", "western sahara"],
  ["lxWS_H_turban_04_blue_una", "western sahara"],
  ["lxWS_H_turban_04_red", "western sahara"],
  ["lxWS_H_turban_04_yellow", "western sahara"],
  ["lxWS_H_ssh40_black", "western sahara"],
  ["lxWS_H_ssh40_blue", "western sahara"],
  ["lxWS_H_ssh40_green", "western sahara"],
  ["lxWS_H_ssh40_sand", "western sahara"],
  ["lxWS_H_ssh40_white", "western sahara"],
  ["lxWS_H_ssh40_un", "western sahara"],
  ["lxWS_H_bmask_base", "western sahara"],
  ["lxWS_H_bmask_hex", "western sahara"],
  ["lxWS_H_bmask_ghex", "western sahara"],
  ["lxWS_H_bmask_white", "western sahara"],
  ["lxWS_H_bmask_yellow", "western sahara"],
  ["lxWS_H_bmask_camo01", "western sahara"],
  ["lxWS_H_bmask_camo02", "western sahara"],
  ["lxWS_H_Headset", "western sahara"],
  ["lxWS_H_cloth_5_A", "western sahara"],
  ["lxWS_H_cloth_5_B", "western sahara"],
  ["lxWS_H_cloth_5_C", "western sahara"],
  ["lxWS_H_PASGT_basic_UN_F", "western sahara"],
  ["lxWS_H_PASGT_goggles_UN_F", "western sahara"],
  ["lxWS_H_PASGT_goggles_black_F", "western sahara"],
  ["lxWS_H_PASGT_goggles_white_F", "western sahara"],
  ["lxWS_H_PASGT_goggles_olive_F", "western sahara"],
  ["lxWS_H_Tank_tan_F", "western sahara"],
  ["lxWS_H_CapB_rvs_blk_ION", "western sahara"],
  ["Rev_H_MCH_BasicNet_FDB_Marine_EF", "expeditionary forces"],
  ["H_HBK_MTPA", "contact"],
  ["H_HBK_MTPA_Peltor", "contact"],
  ["H_HBK_MTPA_Chops", "contact"],
  ["H_HBK_MTPA_Ears", "contact"],
  ["H_HBK_MTPT", "contact"],
  ["H_HBK_MTPT_Peltor", "contact"],
  ["H_HBK_MTPT_Chops", "contact"],
  ["H_HBK_MTPT_Ears", "contact"],
  ["H_HBK_MTPW", "contact"],
  ["H_HBK_MTPW_Peltor", "contact"],
  ["H_HBK_MTPW_Chops", "contact"],
  ["H_HBK_MTPW_Ears", "contact"],
  ["H_HBK_MTPS", "contact"],
  ["H_HBK_MTPS_Peltor", "contact"],
  ["H_HBK_MTPS_Chops", "contact"],
  ["H_HBK_MTPS_Ears", "contact"],
  ["H_HBK_OCPA", "contact"],
  ["H_HBK_OCPA_Peltor", "contact"],
  ["H_HBK_OCPA_Chops", "contact"],
  ["H_HBK_OCPA_Ears", "contact"],
  ["H_HBK_OCPT", "contact"],
  ["H_HBK_OCPT_Peltor", "contact"],
  ["H_HBK_OCPT_Chops", "contact"],
  ["H_HBK_OCPT_Ears", "contact"],
  ["H_HBK_OCPW", "contact"],
  ["H_HBK_OCPW_Peltor", "contact"],
  ["H_HBK_OCPW_Chops", "contact"],
  ["H_HBK_OCPW_Ears", "contact"],
  ["H_HBK_OCPS", "contact"],
  ["H_HBK_OCPS_Peltor", "contact"],
  ["H_HBK_OCPS_Chops", "contact"],
  ["H_HBK_OCPS_Ears", "contact"],
  ["H_HBK_MARPATW", "contact"],
  ["H_HBK_MARPATW_Peltor", "contact"],
  ["H_HBK_MARPATW_Chops", "contact"],
  ["H_HBK_MARPATW_Ears", "contact"],
  ["H_HBK_MARPATD", "contact"],
  ["H_HBK_MARPATD_Peltor", "contact"],
  ["H_HBK_MARPATD_Chops", "contact"],
  ["H_HBK_MARPATD_Ears", "contact"],
  ["H_HBK_MARPATS", "contact"],
  ["H_HBK_MARPATS_Peltor", "contact"],
  ["H_HBK_MARPATS_Chops", "contact"],
  ["H_HBK_MARPATS_Ears", "contact"],
  ["H_HBK_EMRD", "contact"],
  ["H_HBK_EMRD_Peltor", "contact"],
  ["H_HBK_EMRD_Chops", "contact"],
  ["H_HBK_EMRD_Ears", "contact"],
  ["H_HBK_EMRW", "contact"],
  ["H_HBK_EMRW_Peltor", "contact"],
  ["H_HBK_EMRW_Chops", "contact"],
  ["H_HBK_EMRW_Ears", "contact"],
  ["H_HBK_EMRS", "contact"],
  ["H_HBK_EMRS_Peltor", "contact"],
  ["H_HBK_EMRS_Chops", "contact"],
  ["H_HBK_EMRS_Ears", "contact"],
  ["H_HBK_CCED", "contact"],
  ["H_HBK_CCED_Peltor", "contact"],
  ["H_HBK_CCED_Chops", "contact"],
  ["H_HBK_CCED_Ears", "contact"],
  ["H_HBK_CCEW", "contact"],
  ["H_HBK_CCEW_Peltor", "contact"],
  ["H_HBK_CCEW_Chops", "contact"],
  ["H_HBK_CCEW_Ears", "contact"],
  ["H_HBK_CCES", "contact"],
  ["H_HBK_CCES_Peltor", "contact"],
  ["H_HBK_CCES_Chops", "contact"],
  ["H_HBK_CCES_Ears", "contact"],
  ["H_HBK_FLKD", "contact"],
  ["H_HBK_FLKD_Peltor", "contact"],
  ["H_HBK_FLKD_Chops", "contact"],
  ["H_HBK_FLKD_Ears", "contact"],
  ["H_HBK_FLKW", "contact"],
  ["H_HBK_FLKW_Peltor", "contact"],
  ["H_HBK_FLKW_Chops", "contact"],
  ["H_HBK_FLKW_Ears", "contact"],
  ["H_HBK_FLKS", "contact"],
  ["H_HBK_FLKS_Peltor", "contact"],
  ["H_HBK_FLKS_Chops", "contact"],
  ["H_HBK_FLKS_Ears", "contact"],
  ["H_HBK_AMCA", "contact"],
  ["H_HBK_AMCA_Peltor", "contact"],
  ["H_HBK_AMCA_Chops", "contact"],
  ["H_HBK_AMCA_Ears", "contact"],
  ["H_HBK_AMCT", "contact"],
  ["H_HBK_AMCT_Peltor", "contact"],
  ["H_HBK_AMCT_Chops", "contact"],
  ["H_HBK_AMCT_Ears", "contact"],
  ["H_HBK_AMCW", "contact"],
  ["H_HBK_AMCW_Peltor", "contact"],
  ["H_HBK_AMCW_Chops", "contact"],
  ["H_HBK_AMCW_Ears", "contact"],
  ["H_HBK_AMCS", "contact"],
  ["H_HBK_AMCS_Peltor", "contact"],
  ["H_HBK_AMCS_Chops", "contact"],
  ["H_HBK_AMCS_Ears", "contact"],
  ["H_HBK_HEXA", "contact"],
  ["H_HBK_HEXA_Peltor", "contact"],
  ["H_HBK_HEXA_Chops", "contact"],
  ["H_HBK_HEXA_Ears", "contact"],
  ["H_HBK_HEXT", "contact"],
  ["H_HBK_HEXT_Peltor", "contact"],
  ["H_HBK_HEXT_Chops", "contact"],
  ["H_HBK_HEXT_Ears", "contact"],
  ["H_HBK_HEXW", "contact"],
  ["H_HBK_HEXW_Peltor", "contact"],
  ["H_HBK_HEXW_Chops", "contact"],
  ["H_HBK_HEXW_Ears", "contact"],
  ["H_HBK_HEXTG", "contact"],
  ["H_HBK_HEXTG_Peltor", "contact"],
  ["H_HBK_HEXTG_Chops", "contact"],
  ["H_HBK_HEXTG_Ears", "contact"],
  ["H_HBK_HEXS", "contact"],
  ["H_HBK_HEXS_Peltor", "contact"],
  ["H_HBK_HEXS_Chops", "contact"],
  ["H_HBK_HEXS_Ears", "contact"],
  ["H_HBK_CADD", "contact"],
  ["H_HBK_CADD_Peltor", "contact"],
  ["H_HBK_CADD_Chops", "contact"],
  ["H_HBK_CADD_Ears", "contact"],
  ["H_HBK_CADW", "contact"],
  ["H_HBK_CADW_Peltor", "contact"],
  ["H_HBK_CADW_Chops", "contact"],
  ["H_HBK_CADW_Ears", "contact"],
  ["H_HBK_CADS", "contact"],
  ["H_HBK_CADS_Peltor", "contact"],
  ["H_HBK_CADS_Chops", "contact"],
  ["H_HBK_CADS_Ears", "contact"],
  ["H_HBK_GEO", "contact"],
  ["H_HBK_GEO_Peltor", "contact"],
  ["H_HBK_GEO_Chops", "contact"],
  ["H_HBK_GEO_Ears", "contact"],
  ["H_HBK_GEOC", "contact"],
  ["H_HBK_GEOC_Peltor", "contact"],
  ["H_HBK_GEOC_Chops", "contact"],
  ["H_HBK_GEOC_Ears", "contact"],
  ["H_HBK_GEOS", "contact"],
  ["H_HBK_GEOS_Peltor", "contact"],
  ["H_HBK_GEOS_Chops", "contact"],
  ["H_HBK_GEOS_Ears", "contact"],
  ["H_HBK_GTGR", "contact"],
  ["H_HBK_GTGR_Peltor", "contact"],
  ["H_HBK_GTGR_Chops", "contact"],
  ["H_HBK_GTGR_Ears", "contact"],
  ["H_HBK_GTGRC", "contact"],
  ["H_HBK_GTGRC_Peltor", "contact"],
  ["H_HBK_GTGRC_Chops", "contact"],
  ["H_HBK_GTGRC_Ears", "contact"],
  ["H_HBK_GTGRS", "contact"],
  ["H_HBK_GTGRS_Peltor", "contact"],
  ["H_HBK_GTGRS_Chops", "contact"],
  ["H_HBK_GTGRS_Ears", "contact"],
  ["H_HBK_T07D", "contact"],
  ["H_HBK_T07D_Peltor", "contact"],
  ["H_HBK_T07D_Chops", "contact"],
  ["H_HBK_T07D_Ears", "contact"],
  ["H_HBK_T07W", "contact"],
  ["H_HBK_T07W_Peltor", "contact"],
  ["H_HBK_T07W_Chops", "contact"],
  ["H_HBK_T07W_Ears", "contact"],
  ["H_HBK_T07S", "contact"],
  ["H_HBK_T07S_Peltor", "contact"],
  ["H_HBK_T07S_Chops", "contact"],
  ["H_HBK_T07S_Ears", "contact"],
  ["H_HBK_JIED", "contact"],
  ["H_HBK_JIED_Peltor", "contact"],
  ["H_HBK_JIED_Chops", "contact"],
  ["H_HBK_JIED_Ears", "contact"],
  ["H_HBK_JIEW", "contact"],
  ["H_HBK_JIEW_Peltor", "contact"],
  ["H_HBK_JIEW_Chops", "contact"],
  ["H_HBK_JIEW_Ears", "contact"],
  ["H_HBK_JIES", "contact"],
  ["H_HBK_JIES_Peltor", "contact"],
  ["H_HBK_JIES_Chops", "contact"],
  ["H_HBK_JIES_Ears", "contact"],
  ["U_CBRN_MTPA", "contact"],
  ["U_CombatFatigues_MTPA", "contact"],
  ["U_Fatigues_MTPA", "contact"],
  ["U_HWFATIGUES_MTPA", "contact"],
  ["U_CBRN_MTPT", "contact"],
  ["U_CombatFatigues_MTPT", "contact"],
  ["U_Fatigues_MTPT", "contact"],
  ["U_HWFATIGUES_MTPT", "contact"],
  ["U_CBRN_MTPW", "contact"],
  ["U_CombatFatigues_MTPW", "contact"],
  ["U_Fatigues_MTPW", "contact"],
  ["U_HWFATIGUES_MTPW", "contact"],
  ["U_CBRN_MTPS", "contact"],
  ["U_CombatFatigues_MTPS", "contact"],
  ["U_Fatigues_MTPS", "contact"],
  ["U_HWFATIGUES_MTPS", "contact"],
  ["U_CBRN_OCPA", "contact"],
  ["U_CombatFatigues_OCPA", "contact"],
  ["U_Fatigues_OCPA", "contact"],
  ["U_HWFATIGUES_OCPA", "contact"],
  ["U_CBRN_OCPT", "contact"],
  ["U_CombatFatigues_OCPT", "contact"],
  ["U_Fatigues_OCPT", "contact"],
  ["U_HWFATIGUES_OCPT", "contact"],
  ["U_CBRN_OCPW", "contact"],
  ["U_CombatFatigues_OCPW", "contact"],
  ["U_Fatigues_OCPW", "contact"],
  ["U_HWFATIGUES_OCPW", "contact"],
  ["U_CBRN_OCPS", "contact"],
  ["U_CombatFatigues_OCPS", "contact"],
  ["U_Fatigues_OCPS", "contact"],
  ["U_HWFATIGUES_OCPS", "contact"],
  ["U_CBRN_MARPATW", "contact"],
  ["U_CombatFatigues_MARPATW", "contact"],
  ["U_Fatigues_MARPATW", "contact"],
  ["U_HWFATIGUES_MARPATW", "contact"],
  ["U_CBRN_MARPATD", "contact"],
  ["U_CombatFatigues_MARPATD", "contact"],
  ["U_Fatigues_MARPATD", "contact"],
  ["U_HWFATIGUES_MARPATD", "contact"],
  ["U_CBRN_MARPATS", "contact"],
  ["U_CombatFatigues_MARPATS", "contact"],
  ["U_Fatigues_MARPATS", "contact"],
  ["U_HWFATIGUES_MARPATS", "contact"],
  ["U_CBRN_EMRW", "contact"],
  ["U_CombatFatigues_EMRW", "contact"],
  ["U_Fatigues_EMRW", "contact"],
  ["U_HWFATIGUES_EMRW", "contact"],
  ["U_CBRN_EMRD", "contact"],
  ["U_CombatFatigues_EMRD", "contact"],
  ["U_Fatigues_EMRD", "contact"],
  ["U_HWFATIGUES_EMRD", "contact"],
  ["U_CBRN_EMRS", "contact"],
  ["U_CombatFatigues_EMRS", "contact"],
  ["U_Fatigues_EMRS", "contact"],
  ["U_HWFATIGUES_EMRS", "contact"],
  ["U_CBRN_FLKW", "contact"],
  ["U_CombatFatigues_FLKW", "contact"],
  ["U_Fatigues_FLKW", "contact"],
  ["U_HWFATIGUES_FLKW", "contact"],
  ["U_CBRN_FLKD", "contact"],
  ["U_CombatFatigues_FLKD", "contact"],
  ["U_Fatigues_FLKD", "contact"],
  ["U_HWFATIGUES_FLKD", "contact"],
  ["U_CBRN_FLKS", "contact"],
  ["U_CombatFatigues_FLKS", "contact"],
  ["U_Fatigues_FLKS", "contact"],
  ["U_HWFATIGUES_FLKS", "contact"],
  ["U_CBRN_CCEW", "contact"],
  ["U_CombatFatigues_CCEW", "contact"],
  ["U_Fatigues_CCEW", "contact"],
  ["U_HWFATIGUES_CCEW", "contact"],
  ["U_CBRN_CCED", "contact"],
  ["U_CombatFatigues_CCED", "contact"],
  ["U_Fatigues_CCED", "contact"],
  ["U_HWFATIGUES_CCED", "contact"],
  ["U_CBRN_CCES", "contact"],
  ["U_CombatFatigues_CCES", "contact"],
  ["U_Fatigues_CCES", "contact"],
  ["U_HWFATIGUES_CCES", "contact"],
  ["U_CBRN_AMCA", "contact"],
  ["U_CombatFatigues_AMCA", "contact"],
  ["U_Fatigues_AMCA", "contact"],
  ["U_HWFATIGUES_AMCA", "contact"],
  ["U_CBRN_AMCT", "contact"],
  ["U_CombatFatigues_AMCT", "contact"],
  ["U_Fatigues_AMCT", "contact"],
  ["U_HWFATIGUES_AMCT", "contact"],
  ["U_CBRN_AMCW", "contact"],
  ["U_CombatFatigues_AMCW", "contact"],
  ["U_Fatigues_AMCW", "contact"],
  ["U_HWFATIGUES_AMCW", "contact"],
  ["U_CBRN_AMCS", "contact"],
  ["U_CombatFatigues_AMCS", "contact"],
  ["U_Fatigues_AMCS", "contact"],
  ["U_HWFATIGUES_AMCS", "contact"],
  ["U_CBRN_HEXA", "contact"],
  ["U_CombatFatigues_HEXA", "contact"],
  ["U_Fatigues_HEXA", "contact"],
  ["U_HWFATIGUES_HEXA", "contact"],
  ["U_CBRN_HEXT", "contact"],
  ["U_CombatFatigues_HEXT", "contact"],
  ["U_Fatigues_HEXT", "contact"],
  ["U_HWFATIGUES_HEXT", "contact"],
  ["U_CBRN_HEXW", "contact"],
  ["U_CombatFatigues_HEXW", "contact"],
  ["U_Fatigues_HEXW", "contact"],
  ["U_HWFATIGUES_HEXW", "contact"],
  ["U_CBRN_HEXTG", "contact"],
  ["U_CombatFatigues_HEXTG", "contact"],
  ["U_Fatigues_HEXTG", "contact"],
  ["U_HWFATIGUES_HEXTG", "contact"],
  ["U_CBRN_HEXS", "contact"],
  ["U_CombatFatigues_HEXS", "contact"],
  ["U_Fatigues_HEXS", "contact"],
  ["U_HWFATIGUES_HEXS", "contact"],
  ["U_CBRN_CADD", "contact"],
  ["U_CombatFatigues_CADD", "contact"],
  ["U_Fatigues_CADD", "contact"],
  ["U_HWFATIGUES_CADD", "contact"],
  ["U_CBRN_CADW", "contact"],
  ["U_CombatFatigues_CADW", "contact"],
  ["U_Fatigues_CADW", "contact"],
  ["U_HWFATIGUES_CADW", "contact"],
  ["U_CBRN_CADS", "contact"],
  ["U_CombatFatigues_CADS", "contact"],
  ["U_Fatigues_CADS", "contact"],
  ["U_HWFATIGUES_CADS", "contact"],
  ["U_CBRN_T07W", "contact"],
  ["U_CombatFatigues_T07W", "contact"],
  ["U_Fatigues_T07W", "contact"],
  ["U_HWFATIGUES_T07W", "contact"],
  ["U_CBRN_T07D", "contact"],
  ["U_CombatFatigues_T07D", "contact"],
  ["U_Fatigues_T07D", "contact"],
  ["U_HWFATIGUES_T07D", "contact"],
  ["U_CBRN_T07S", "contact"],
  ["U_CombatFatigues_T07S", "contact"],
  ["U_Fatigues_T07S", "contact"],
  ["U_HWFATIGUES_T07S", "contact"],
  ["V_SmershVest_01_F", "contact"],
  ["V_SmershVest_01_radio_F", "contact"],
  ["V_Condor_01_MTPA", "contact"],
  ["V_Condor_02_MTPA", "contact"],
  ["V_Condor_03_MTPA", "contact"],
  ["V_Condor_01_MTPT", "contact"],
  ["V_Condor_02_MTPT", "contact"],
  ["V_Condor_03_MTPT", "contact"],
  ["V_Condor_01_MTPW", "contact"],
  ["V_Condor_02_MTPW", "contact"],
  ["V_Condor_03_MTPW", "contact"],
  ["V_Condor_01_MTPS", "contact"],
  ["V_Condor_02_MTPS", "contact"],
  ["V_Condor_03_MTPS", "contact"],
  ["V_Condor_01_OCPA", "contact"],
  ["V_Condor_02_OCPA", "contact"],
  ["V_Condor_03_OCPA", "contact"],
  ["V_Condor_01_OCPT", "contact"],
  ["V_Condor_02_OCPT", "contact"],
  ["V_Condor_03_OCPT", "contact"],
  ["V_Condor_01_OCPW", "contact"],
  ["V_Condor_02_OCPW", "contact"],
  ["V_Condor_03_OCPW", "contact"],
  ["V_Condor_01_OCPS", "contact"],
  ["V_Condor_02_OCPS", "contact"],
  ["V_Condor_03_OCPS", "contact"],
  ["V_Condor_01_MARPAT", "contact"],
  ["V_Condor_02_MARPAT", "contact"],
  ["V_Condor_03_MARPAT", "contact"],
  ["V_Condor_01_MARPATS", "contact"],
  ["V_Condor_02_MARPATS", "contact"],
  ["V_Condor_03_MARPATS", "contact"],
  ["V_Condor_01_EMRW", "contact"],
  ["V_Condor_02_EMRW", "contact"],
  ["V_Condor_03_EMRW", "contact"],
  ["V_Condor_01_EMRD", "contact"],
  ["V_Condor_02_EMRD", "contact"],
  ["V_Condor_03_EMRD", "contact"],
  ["V_Condor_01_EMRS", "contact"],
  ["V_Condor_02_EMRS", "contact"],
  ["V_Condor_03_EMRS", "contact"],
  ["V_Condor_01_FLKW", "contact"],
  ["V_Condor_02_FLKW", "contact"],
  ["V_Condor_03_FLKW", "contact"],
  ["V_Condor_01_FLKD", "contact"],
  ["V_Condor_02_FLKD", "contact"],
  ["V_Condor_03_FLKD", "contact"],
  ["V_Condor_01_FLKS", "contact"],
  ["V_Condor_02_FLKS", "contact"],
  ["V_Condor_03_FLKS", "contact"],
  ["V_Condor_01_CCEW", "contact"],
  ["V_Condor_02_CCEW", "contact"],
  ["V_Condor_03_CCEW", "contact"],
  ["V_Condor_01_CCED", "contact"],
  ["V_Condor_02_CCED", "contact"],
  ["V_Condor_03_CCED", "contact"],
  ["V_Condor_01_CCES", "contact"],
  ["V_Condor_02_CCES", "contact"],
  ["V_Condor_03_CCES", "contact"],
  ["V_Condor_01_AMCA", "contact"],
  ["V_Condor_02_AMCA", "contact"],
  ["V_Condor_03_AMCA", "contact"],
  ["V_Condor_01_AMCT", "contact"],
  ["V_Condor_02_AMCT", "contact"],
  ["V_Condor_03_AMCT", "contact"],
  ["V_Condor_01_AMCW", "contact"],
  ["V_Condor_02_AMCW", "contact"],
  ["V_Condor_03_AMCW", "contact"],
  ["V_Condor_01_AMCS", "contact"],
  ["V_Condor_02_AMCS", "contact"],
  ["V_Condor_03_AMCS", "contact"],
  ["V_Condor_01_HEX", "contact"],
  ["V_Condor_02_HEX", "contact"],
  ["V_Condor_03_HEX", "contact"],
  ["V_Condor_01_HEXS", "contact"],
  ["V_Condor_02_HEXS", "contact"],
  ["V_Condor_03_HEXS", "contact"],
  ["V_Condor_01_CADD", "contact"],
  ["V_Condor_02_CADD", "contact"],
  ["V_Condor_03_CADD", "contact"],
  ["V_Condor_01_CADW", "contact"],
  ["V_Condor_02_CADW", "contact"],
  ["V_Condor_03_CADW", "contact"],
  ["V_Condor_01_CADS", "contact"],
  ["V_Condor_02_CADS", "contact"],
  ["V_Condor_03_CADS", "contact"],
  ["V_Condor_01_T07W", "contact"],
  ["V_Condor_02_T07W", "contact"],
  ["V_Condor_03_T07W", "contact"],
  ["V_Condor_01_T07D", "contact"],
  ["V_Condor_02_T07D", "contact"],
  ["V_Condor_03_T07D", "contact"],
  ["V_Condor_01_T07S", "contact"],
  ["V_Condor_02_T07S", "contact"],
  ["V_Condor_03_T07S", "contact"],
  ["ItemMotionSensor_lxWS", "western sahara"],
  ["hgun_Pistol_Signal_F", "karts"],
  ["optic_AMS", "marksmen"],
  ["optic_AMS_khk", "marksmen"],
  ["optic_AMS_snd", "marksmen"],
  ["optic_KHS_blk", "marksmen"],
  ["optic_KHS_hex", "marksmen"],
  ["optic_KHS_old", "marksmen"],
  ["optic_KHS_tan", "marksmen"],
  ["srifle_DMR_02_F", "marksmen"],
  ["srifle_DMR_02_camo_F", "marksmen"],
  ["srifle_DMR_02_sniper_F", "marksmen"],
  ["srifle_DMR_03_F", "marksmen"],
  ["srifle_DMR_03_khaki_F", "marksmen"],
  ["srifle_DMR_03_tan_F", "marksmen"],
  ["srifle_DMR_03_multicam_F", "marksmen"],
  ["srifle_DMR_03_woodland_F", "marksmen"],
  ["srifle_DMR_04_F", "marksmen"],
  ["srifle_DMR_04_Tan_F", "marksmen"],
  ["srifle_DMR_05_blk_F", "marksmen"],
  ["srifle_DMR_05_hex_F", "marksmen"],
  ["srifle_DMR_05_tan_f", "marksmen"],
  ["srifle_DMR_06_camo_F", "marksmen"],
  ["srifle_DMR_06_olive_F", "marksmen"],
  ["MMG_01_hex_F", "marksmen"],
  ["MMG_01_tan_F", "marksmen"],
  ["MMG_02_camo_F", "marksmen"],
  ["MMG_02_black_F", "marksmen"],
  ["MMG_02_sand_F", "marksmen"],
  ["TacVest_V1", "jets"],
  ["NVGogglesB_blk_F", "apex"],
  ["NVGogglesB_grn_F", "apex"],
  ["NVGogglesB_gry_F", "apex"],
  ["muzzle_snds_58_blk_F", "apex"],
  ["muzzle_snds_58_ghex_F", "apex"],
  ["muzzle_snds_58_hex_F", "apex"],
  ["muzzle_snds_65_TI_blk_F", "apex"],
  ["muzzle_snds_65_TI_hex_F", "apex"],
  ["muzzle_snds_65_TI_ghex_F", "apex"],
  ["optic_ERCO_blk_F", "apex"],
  ["optic_ERCO_khk_F", "apex"],
  ["optic_ERCO_snd_F", "apex"],
  ["launch_RPG7_F", "apex"],
  ["srifle_DMR_07_blk_F", "apex"],
  ["srifle_DMR_07_hex_F", "apex"],
  ["srifle_DMR_07_ghex_F", "apex"],
  ["LMG_03_F", "apex"],
  ["hgun_Pistol_01_F", "apex"],
  ["arifle_AK12_F", "apex"],
  ["arifle_AK12_GL_F", "apex"],
  ["arifle_AKM_F", "apex"],
  ["arifle_AKM_FL_F", "apex"],
  ["arifle_AKS_F", "apex"],
  ["arifle_ARX_blk_F", "apex"],
  ["arifle_ARX_ghex_F", "apex"],
  ["arifle_ARX_hex_F", "apex"],
  ["arifle_CTAR_blk_F", "apex"],
  ["arifle_CTAR_hex_F", "apex"],
  ["arifle_CTAR_ghex_F", "apex"],
  ["arifle_CTAR_GL_blk_F", "apex"],
  ["arifle_CTAR_GL_hex_F", "apex"],
  ["arifle_CTAR_GL_ghex_F", "apex"],
  ["arifle_CTARS_blk_F", "apex"],
  ["arifle_CTARS_hex_F", "apex"],
  ["arifle_CTARS_ghex_F", "apex"],
  ["arifle_SPAR_01_blk_F", "apex"],
  ["arifle_SPAR_01_khk_F", "apex"],
  ["arifle_SPAR_01_snd_F", "apex"],
  ["arifle_SPAR_01_GL_blk_F", "apex"],
  ["arifle_SPAR_01_GL_khk_F", "apex"],
  ["arifle_SPAR_01_GL_snd_F", "apex"],
  ["arifle_SPAR_02_blk_F", "apex"],
  ["arifle_SPAR_02_khk_F", "apex"],
  ["arifle_SPAR_02_snd_F", "apex"],
  ["arifle_SPAR_03_blk_F", "apex"],
  ["arifle_SPAR_03_khk_F", "apex"],
  ["arifle_SPAR_03_snd_F", "apex"],
  ["SMG_05_F", "apex"],
  ["U_B_T_FullGhillie_tna_F", "marksmen"],
  ["U_B_CTRG_Soldier_F", "apex"],
  ["U_B_CTRG_Soldier_2_F", "apex"],
  ["U_B_CTRG_Soldier_3_F", "apex"],
  ["U_B_CTRG_Soldier_Arid_F", "apex"],
  ["U_B_CTRG_Soldier_2_Arid_F", "apex"],
  ["U_B_CTRG_Soldier_3_Arid_F", "apex"],
  ["U_B_GEN_Soldier_F", "apex"],
  ["U_B_GEN_Commander_F", "apex"],
  ["U_O_T_FullGhillie_tna_F", "marksmen"],
  ["U_O_V_Soldier_Viper_F", "apex"],
  ["U_O_V_Soldier_Viper_hex_F", "apex"],
  ["U_I_C_Soldier_Para_1_F", "apex"],
  ["U_I_C_Soldier_Para_2_F", "apex"],
  ["U_I_C_Soldier_Para_3_F", "apex"],
  ["U_I_C_Soldier_Para_4_F", "apex"],
  ["U_I_C_Soldier_Para_5_F", "apex"],
  ["U_I_C_Soldier_Bandit_1_F", "apex"],
  ["U_I_C_Soldier_Bandit_2_F", "apex"],
  ["U_I_C_Soldier_Bandit_3_F", "apex"],
  ["U_I_C_Soldier_Bandit_4_F", "apex"],
  ["U_I_C_Soldier_Bandit_5_F", "apex"],
  ["U_I_C_Soldier_Camo_F", "apex"],
  ["U_C_man_sport_1_F", "apex"],
  ["U_C_man_sport_2_F", "apex"],
  ["U_C_man_sport_3_F", "apex"],
  ["H_HelmetB_TI_tna_F", "apex"],
  ["H_HelmetB_TI_arid_F", "apex"],
  ["H_HelmetO_ViperSP_hex_F", "apex"],
  ["H_HelmetO_ViperSP_ghex_F", "apex"],
  ["V_TacChestrig_grn_F", "apex"],
  ["V_TacChestrig_oli_F", "apex"],
  ["V_TacChestrig_cbr_F", "apex"],
  ["Camera_lxWS", "western sahara"],
  ["arifle_Galat_lxWS", "western sahara"],
  ["arifle_SLR_lxWS", "western sahara"],
  ["arifle_SLR_D_lxWS", "western sahara"],
  ["arifle_SLR_GL_lxWS", "western sahara"],
  ["arifle_SLR_V_lxWS", "western sahara"],
  ["arifle_SLR_V_GL_lxWS", "western sahara"],
  ["arifle_Velko_lxWS", "western sahara"],
  ["arifle_XMS_lxWS", "western sahara"],
  ["arifle_XMS_M_lxWS", "western sahara"],
  ["arifle_XMS_Shot_lxWS", "western sahara"],
  ["arifle_XMS_GL_lxWS", "western sahara"],
  ["arifle_XMS_Sand_lxWS", "western sahara"],
  ["arifle_XMS_M_Sand_lxWS", "western sahara"],
  ["arifle_XMS_Shot_Sand_lxWS", "western sahara"],
  ["arifle_XMS_GL_Sand_lxWS", "western sahara"],
  ["arifle_XMS_khk_lxWS", "western sahara"],
  ["arifle_XMS_M_khk_lxWS", "western sahara"],
  ["arifle_XMS_Shot_khk_lxWS", "western sahara"],
  ["arifle_XMS_GL_khk_lxWS", "western sahara"],
  ["arifle_XMS_Camo_lxWS", "western sahara"],
  ["arifle_XMS_M_Camo_lxWS", "western sahara"],
  ["arifle_XMS_Shot_Camo_lxWS", "western sahara"],
  ["arifle_XMS_GL_Camo_lxWS", "western sahara"],
  ["arifle_XMS_Gray_lxWS", "western sahara"],
  ["arifle_XMS_M_Gray_lxWS", "western sahara"],
  ["arifle_XMS_Shot_Gray_lxWS", "western sahara"],
  ["arifle_XMS_GL_Gray_lxWS", "western sahara"],
  ["suppressor_h_lxWS", "western sahara"],
  ["suppressor_h_snake_lxWS", "western sahara"],
  ["suppressor_h_sand_lxWS", "western sahara"],
  ["suppressor_h_khaki_lxWS", "western sahara"],
  ["suppressor_h_arid_lxWS", "western sahara"],
  ["suppressor_h_lush_lxWS", "western sahara"],
  ["suppressor_l_lxWS", "western sahara"],
  ["suppressor_l_snake_lxWS", "western sahara"],
  ["suppressor_l_sand_lxWS", "western sahara"],
  ["suppressor_l_khaki_lxWS", "western sahara"],
  ["suppressor_l_arid_lxWS", "western sahara"],
  ["suppressor_l_lush_lxWS", "western sahara"],
  ["suppressor_l_camo_lxWS", "western sahara"],
  ["suppressor_m_lxWS", "western sahara"],
  ["suppressor_m_snake_lxWS", "western sahara"],
  ["suppressor_m_sand_lxWS", "western sahara"],
  ["suppressor_m_khaki_lxWS", "western sahara"],
  ["suppressor_m_arid_lxWS", "western sahara"],
  ["suppressor_m_lush_lxWS", "western sahara"],
  ["muzzle_snds_12Gauge_lxWS", "western sahara"],
  ["muzzle_snds_12Gauge_snake_lxWS", "western sahara"],
  ["optic_ACO_grn_camo_lxWS", "western sahara"],
  ["optic_ACO_camo_lxWS", "western sahara"],
  ["optic_r1_high_lxWS", "western sahara"],
  ["optic_r1_low_lxWS", "western sahara"],
  ["optic_r1_high_khaki_lxWS", "western sahara"],
  ["optic_r1_low_khaki_lxWS", "western sahara"],
  ["optic_r1_high_sand_lxWS", "western sahara"],
  ["optic_r1_high_black_sand_lxWS", "western sahara"],
  ["optic_r1_low_sand_lxWS", "western sahara"],
  ["optic_r1_high_snake_lxWS", "western sahara"],
  ["optic_r1_low_snake_lxWS", "western sahara"],
  ["optic_r1_high_arid_lxWS", "western sahara"],
  ["optic_r1_low_arid_lxWS", "western sahara"],
  ["optic_r1_high_lush_lxWS", "western sahara"],
  ["optic_r1_low_lush_lxWS", "western sahara"],
  ["acc_pointer_IR_arid_lxWS", "western sahara"],
  ["acc_pointer_IR_lush_lxWS", "western sahara"],
  ["acc_pointer_IR_snake_lxWS", "western sahara"],
  ["acc_pointer_IR_sand_lxWS", "western sahara"],
  ["optic_Holosight_snake_lxWS", "western sahara"],
  ["optic_Holosight_smg_snake_lxWS", "western sahara"],
  ["optic_Hamr_snake_lxWS", "western sahara"],
  ["optic_Hamr_arid_lxWS", "western sahara"],
  ["optic_Hamr_lush_lxWS", "western sahara"],
  ["optic_Hamr_sand_lxWS", "western sahara"],
  ["optic_Arco_hex_lxWS", "western sahara"],
  ["optic_DMS_snake_lxWS", "western sahara"],
  ["saber_light_lxWS", "western sahara"],
  ["saber_light_ir_lxWS", "western sahara"],
  ["saber_light_arid_lxWS", "western sahara"],
  ["saber_light_ir_arid_lxWS", "western sahara"],
  ["saber_light_lush_lxWS", "western sahara"],
  ["saber_light_ir_lush_lxWS", "western sahara"],
  ["saber_light_sand_lxWS", "western sahara"],
  ["saber_light_ir_sand_lxWS", "western sahara"],
  ["saber_light_khaki_lxWS", "western sahara"],
  ["saber_light_ir_khaki_lxWS", "western sahara"],
  ["saber_light_snake_lxWS", "western sahara"],
  ["saber_light_ir_snake_lxWS", "western sahara"],
  ["LMG_S77_lxWS", "western sahara"],
  ["LMG_S77_AAF_lxWS", "western sahara"],
  ["LMG_S77_Hex_lxWS", "western sahara"],
  ["LMG_S77_GHex_lxWS", "western sahara"],
  ["LMG_S77_Desert_lxWS", "western sahara"],
  ["LMG_S77_Compact_lxWS", "western sahara"],
  ["LMG_S77_Compact_Snakeskin_lxWS", "western sahara"],
  ["arifle_Galat_worn_lxWS", "western sahara"],
  ["glaunch_GLX_lxWS", "western sahara"],
  ["glaunch_GLX_snake_lxWS", "western sahara"],
  ["glaunch_GLX_hex_lxWS", "western sahara"],
  ["glaunch_GLX_ghex_lxWS", "western sahara"],
  ["glaunch_GLX_camo_lxWS", "western sahara"],
  ["glaunch_GLX_tan_lxWS", "western sahara"],
  ["arifle_SLR_V_camo_lxWS", "western sahara"],
  ["arifle_SLR_Para_lxWS", "western sahara"],
  ["arifle_SLR_Para_snake_lxWS", "western sahara"],
  ["arifle_VelkoR5_lxWS", "western sahara"],
  ["arifle_VelkoR5_GL_lxWS", "western sahara"],
  ["arifle_VelkoR5_snake_lxWS", "western sahara"],
  ["arifle_VelkoR5_GL_snake_lxWS", "western sahara"],
  ["sgun_aa40_lxWS", "western sahara"],
  ["sgun_aa40_tan_lxWS", "western sahara"],
  ["sgun_aa40_snake_lxWS", "western sahara"],
  ["V_DeckCrew_yellow_F", "jets"],
  ["V_DeckCrew_blue_F", "jets"],
  ["V_DeckCrew_green_F", "jets"],
  ["V_DeckCrew_red_F", "jets"],
  ["V_DeckCrew_white_F", "jets"],
  ["V_DeckCrew_brown_F", "jets"],
  ["V_DeckCrew_violet_F", "jets"],
  ["U_C_Paramedic_01_F", "laws of war"],
  ["U_C_Mechanic_01_F", "laws of war"],
  ["H_Hat_Safari_sand_F", "laws of war"],
  ["H_Hat_Safari_olive_F", "laws of war"],
  ["H_Construction_basic_yellow_F", "laws of war"],
  ["H_Construction_basic_white_F", "laws of war"],
  ["H_Construction_basic_orange_F", "laws of war"],
  ["H_Construction_basic_red_F", "laws of war"],
  ["H_Construction_basic_vrana_F", "laws of war"],
  ["H_Construction_basic_black_F", "laws of war"],
  ["H_Construction_earprot_yellow_F", "laws of war"],
  ["H_Construction_earprot_white_F", "laws of war"],
  ["H_Construction_earprot_orange_F", "laws of war"],
  ["H_Construction_earprot_red_F", "laws of war"],
  ["H_Construction_earprot_vrana_F", "laws of war"],
  ["H_Construction_earprot_black_F", "laws of war"],
  ["H_Construction_headset_yellow_F", "laws of war"],
  ["H_Construction_headset_white_F", "laws of war"],
  ["H_Construction_headset_orange_F", "laws of war"],
  ["H_Construction_headset_red_F", "laws of war"],
  ["H_Construction_headset_vrana_F", "laws of war"],
  ["H_Construction_headset_black_F", "laws of war"],
  ["H_EarProtectors_yellow_F", "laws of war"],
  ["H_EarProtectors_white_F", "laws of war"],
  ["H_EarProtectors_orange_F", "laws of war"],
  ["H_EarProtectors_red_F", "laws of war"],
  ["H_EarProtectors_black_F", "laws of war"],
  ["H_HeadSet_yellow_F", "laws of war"],
  ["H_HeadSet_white_F", "laws of war"],
  ["H_HeadSet_orange_F", "laws of war"],
  ["H_HeadSet_red_F", "laws of war"],
  ["H_HeadSet_black_F", "laws of war"],
  ["H_PASGT_basic_blue_press_F", "laws of war"],
  ["H_PASGT_basic_blue_F", "laws of war"],
  ["H_PASGT_basic_white_F", "laws of war"],
  ["H_PASGT_basic_olive_F", "laws of war"],
  ["H_PASGT_basic_black_F", "laws of war"],
  ["H_PASGT_neckprot_blue_press_F", "laws of war"],
  ["H_HeadBandage_stained_F", "laws of war"],
  ["H_HeadBandage_clean_F", "laws of war"],
  ["H_HeadBandage_bloody_F", "laws of war"],
  ["H_WirelessEarpiece_F", "laws of war"],
  ["V_Plain_medical_F", "laws of war"],
  ["V_Plain_crystal_F", "laws of war"],
  ["V_Pocketed_olive_F", "laws of war"],
  ["V_Pocketed_coyote_F", "laws of war"],
  ["V_Pocketed_black_F", "laws of war"],
  ["V_Safety_yellow_F", "laws of war"],
  ["V_Safety_orange_F", "laws of war"],
  ["V_Safety_blue_F", "laws of war"],
  ["V_LegStrapBag_black_F", "laws of war"],
  ["V_LegStrapBag_coyote_F", "laws of war"],
  ["V_LegStrapBag_olive_F", "laws of war"],
  ["V_EOD_blue_F", "laws of war"],
  ["V_EOD_olive_F", "laws of war"],
  ["V_EOD_coyote_F", "laws of war"],
  ["V_EOD_IDAP_blue_F", "laws of war"],
  ["U_Tank_green_F", "tanks"],
  ["optic_ico_01_f", "contact"],
  ["optic_ico_01_black_f", "contact"],
  ["optic_ico_01_sand_f", "contact"],
  ["optic_ico_01_camo_f", "contact"],
  ["muzzle_tma_65", "contact"],
  ["acc_esd_01_flashlight", "contact"],
  ["ChemicalDetector_01_olive_F", "contact"],
  ["ChemicalDetector_01_black_F", "contact"],
  ["ChemicalDetector_01_tan_F", "contact"],
  ["ChemicalDetector_01_watch_F", "contact"],
  ["srifle_DMR_06_hunter_F", "contact"],
  ["hgun_esd_01_F", "contact"],
  ["muzzle_antenna_01_f", "contact"],
  ["muzzle_antenna_02_f", "contact"],
  ["muzzle_antenna_03_f", "contact"],
  ["arifle_AK12_lush_F", "apex"],
  ["arifle_AK12_arid_F", "apex"],
  ["arifle_AK12_GL_lush_F", "apex"],
  ["arifle_AK12_GL_arid_F", "apex"],
  ["arifle_RPK12_F", "contact"],
  ["arifle_RPK12_lush_F", "contact"],
  ["arifle_RPK12_arid_F", "contact"],
  ["arifle_AK12U_F", "contact"],
  ["arifle_AK12U_lush_F", "contact"],
  ["arifle_AK12U_arid_F", "contact"],
  ["arifle_MSBS65_F", "contact"],
  ["arifle_MSBS65_Mark_F", "contact"],
  ["arifle_MSBS65_GL_F", "contact"],
  ["arifle_MSBS65_UBS_F", "contact"],
  ["arifle_MSBS65_black_F", "contact"],
  ["arifle_MSBS65_Mark_black_F", "contact"],
  ["arifle_MSBS65_GL_black_F", "contact"],
  ["arifle_MSBS65_UBS_black_F", "contact"],
  ["arifle_MSBS65_sand_F", "contact"],
  ["arifle_MSBS65_Mark_sand_F", "contact"],
  ["arifle_MSBS65_GL_sand_F", "contact"],
  ["arifle_MSBS65_UBS_sand_F", "contact"],
  ["arifle_MSBS65_camo_F", "contact"],
  ["arifle_MSBS65_Mark_camo_F", "contact"],
  ["arifle_MSBS65_GL_camo_F", "contact"],
  ["arifle_MSBS65_UBS_camo_F", "contact"],
  ["sgun_HunterShotgun_01_F", "contact"],
  ["sgun_HunterShotgun_01_sawedoff_F", "contact"],
  ["optic_ACO_grn_desert_RF", "reaction forces"],
  ["optic_ACO_grn_wood_RF", "reaction forces"],
  ["optic_ACO_desert_RF", "reaction forces"],
  ["optic_ACO_wood_RF", "reaction forces"],
  ["optic_VRCO_RF", "reaction forces"],
  ["optic_VRCO_tan_RF", "reaction forces"],
  ["optic_VRCO_khk_RF", "reaction forces"],
  ["optic_VRCO_pistol_RF", "reaction forces"],
  ["optic_rds_RF", "reaction forces"],
  ["optic_MRD_tan_RF", "reaction forces"],
  ["optic_MRD_khk_RF", "reaction forces"],
  ["acc_flashlight_IR_pistol_RF", "reaction forces"],
  ["acc_pointer_IR_pistol_RF", "reaction forces"],
  ["suppressor_127x55_small_RF", "reaction forces"],
  ["suppressor_127x55_big_RF", "reaction forces"],
  ["suppressor_127x55_small_wood_RF", "reaction forces"],
  ["suppressor_127x55_big_wood_RF", "reaction forces"],
  ["suppressor_127x55_small_desert_RF", "reaction forces"],
  ["suppressor_127x55_big_desert_RF", "reaction forces"],
  ["suppressor_65_black_RF", "reaction forces"],
  ["suppressor_65_green_RF", "reaction forces"],
  ["suppressor_65_khaki_RF", "reaction forces"],
  ["suppressor_65_sand_RF", "reaction forces"],
  ["suppressor_65_tan_RF", "reaction forces"],
  ["TiGoggles_RF", "reaction forces"],
  ["TiGoggles_tan_RF", "reaction forces"],
  ["TiGoggles_grn_RF", "reaction forces"],
  ["launch_PSRL1_black_RF", "reaction forces"],
  ["launch_PSRL1_sand_RF", "reaction forces"],
  ["launch_PSRL1_olive_RF", "reaction forces"],
  ["launch_PSRL1_digi_RF", "reaction forces"],
  ["launch_PSRL1_geo_RF", "reaction forces"],
  ["launch_PSRL1_PWS_black_RF", "reaction forces"],
  ["launch_PSRL1_PWS_sand_RF", "reaction forces"],
  ["launch_PSRL1_PWS_olive_RF", "reaction forces"],
  ["launch_PSRL1_PWS_digi_RF", "reaction forces"],
  ["launch_PSRL1_PWS_geo_RF", "reaction forces"],
  ["hgun_DEagle_RF", "reaction forces"],
  ["hgun_DEagle_classic_RF", "reaction forces"],
  ["hgun_DEagle_bronze_RF", "reaction forces"],
  ["hgun_DEagle_copper_RF", "reaction forces"],
  ["hgun_DEagle_gold_RF", "reaction forces"],
  ["hgun_DEagle_camo_RF", "reaction forces"],
  ["hgun_Glock19_RF", "reaction forces"],
  ["hgun_Glock19_Tan_RF", "reaction forces"],
  ["hgun_Glock19_khk_RF", "reaction forces"],
  ["hgun_Glock19_auto_RF", "reaction forces"],
  ["hgun_Glock19_auto_Tan_RF", "reaction forces"],
  ["hgun_Glock19_auto_khk_RF", "reaction forces"],
  ["arifle_ash12_blk_RF", "reaction forces"],
  ["arifle_ash12_desert_RF", "reaction forces"],
  ["arifle_ash12_wood_RF", "reaction forces"],
  ["arifle_ash12_urban_RF", "reaction forces"],
  ["arifle_ash12_GL_blk_RF", "reaction forces"],
  ["arifle_ash12_GL_desert_RF", "reaction forces"],
  ["arifle_ash12_GL_wood_RF", "reaction forces"],
  ["arifle_ash12_GL_urban_RF", "reaction forces"],
  ["arifle_ash12_LR_blk_RF", "reaction forces"],
  ["arifle_ash12_LR_desert_RF", "reaction forces"],
  ["arifle_ash12_LR_wood_RF", "reaction forces"],
  ["arifle_ash12_LR_urban_RF", "reaction forces"],
  ["srifle_h6_tan_rf", "reaction forces"],
  ["srifle_h6_oli_rf", "reaction forces"],
  ["srifle_h6_blk_rf", "reaction forces"],
  ["srifle_h6_digi_rf", "reaction forces"],
  ["srifle_h6_gold_rf", "reaction forces"],
  ["V_lxWS_HarnessO_oli", "western sahara"],
  ["V_lxWS_TacVestIR_oli", "western sahara"],
  ["V_lxWS_UN_Vest_F", "western sahara"],
  ["V_lxWS_UN_Vest_Lite_F", "western sahara"],
  ["U_lxWS_UN_Camo1", "western sahara"],
  ["U_lxWS_SFIA_Officer_1_O", "western sahara"],
  ["U_lxWS_SFIA_soldier_1_O", "western sahara"],
  ["U_lxWS_SFIA_soldier_2_O", "western sahara"],
  ["U_lxWS_SFIA_deserter", "western sahara"],
  ["U_lxWS_Djella_02_Brown", "western sahara"],
  ["U_lxWS_Djella_03_Green", "western sahara"],
  ["U_lxWS_Djella_02_Grey", "western sahara"],
  ["U_lxWS_Djella_02_Sand", "western sahara"],
  ["U_lxWS_C_Djella_01", "western sahara"],
  ["U_lxWS_C_Djella_02", "western sahara"],
  ["U_lxWS_C_Djella_02a", "western sahara"],
  ["U_lxWS_C_Djella_03", "western sahara"],
  ["U_lxWS_C_Djella_04", "western sahara"],
  ["U_lxWS_C_Djella_05", "western sahara"],
  ["U_lxWS_C_Djella_06", "western sahara"],
  ["U_lxWS_C_Djella_07", "western sahara"],
  ["U_lxWS_Tak_01_A", "western sahara"],
  ["U_lxWS_Tak_01_B", "western sahara"],
  ["U_lxWS_Tak_01_C", "western sahara"],
  ["U_lxWS_Tak_02_A", "western sahara"],
  ["U_lxWS_Tak_02_B", "western sahara"],
  ["U_lxWS_Tak_02_C", "western sahara"],
  ["U_lxWS_Tak_03_A", "western sahara"],
  ["U_lxWS_Tak_03_B", "western sahara"],
  ["U_lxWS_Tak_03_C", "western sahara"],
  ["U_lxWS_ION_Casual2", "western sahara"],
  ["U_lxWS_ION_Casual3", "western sahara"],
  ["U_lxWS_ION_Casual4", "western sahara"],
  ["U_lxWS_ION_Casual5", "western sahara"],
  ["U_I_E_Uniform_01_F", "contact"],
  ["U_I_E_Uniform_01_tanktop_F", "contact"],
  ["U_I_E_Uniform_01_shortsleeve_F", "contact"],
  ["U_I_E_Uniform_01_officer_F", "contact"],
  ["U_I_E_Uniform_01_coveralls_F", "contact"],
  ["U_I_E_Uniform_01_sweater_F", "apex"],
  ["U_O_R_Gorka_01_F", "contact"],
  ["U_O_R_Gorka_01_brown_F", "contact"],
  ["U_O_R_Gorka_01_camo_F", "contact"],
  ["U_O_R_Gorka_01_black_F", "contact"],
  ["U_B_CBRN_Suit_01_MTP_F", "contact"],
  ["U_B_CBRN_Suit_01_Tropic_F", "contact"],
  ["U_B_CBRN_Suit_01_Wdl_F", "contact"],
  ["U_I_CBRN_Suit_01_AAF_F", "contact"],
  ["U_I_E_CBRN_Suit_01_EAF_F", "contact"],
  ["U_C_CBRN_Suit_01_Blue_F", "contact"],
  ["U_C_CBRN_Suit_01_White_F", "contact"],
  ["U_I_L_Uniform_01_camo_F", "contact"],
  ["H_HelmetHBK_F", "contact"],
  ["H_HelmetHBK_headset_F", "contact"],
  ["H_HelmetHBK_ear_F", "contact"],
  ["H_HelmetHBK_chops_F", "contact"],
  ["H_HelmetAggressor_F", "contact"],
  ["H_HelmetAggressor_cover_F", "contact"],
  ["H_HelmetAggressor_cover_taiga_F", "contact"],
  ["H_Beret_EAF_01_F", "contact"],
  ["H_Hat_Tinfoil_F", "contact"],
  ["V_CarrierRigKBT_01_EAF_F", "contact"],
  ["V_CarrierRigKBT_01_light_EAF_F", "contact"],
  ["V_CarrierRigKBT_01_heavy_EAF_F", "contact"],
  ["V_CarrierRigKBT_01_Olive_F", "contact"],
  ["V_CarrierRigKBT_01_light_Olive_F", "contact"],
  ["V_CarrierRigKBT_01_heavy_Olive_F", "contact"],
  ["H_PilotHelmetHeli_Black_RF", "reaction forces"],
  ["H_PilotHelmetHeli_Blue_RF", "reaction forces"],
  ["H_PilotHelmetHeli_Green_RF", "reaction forces"],
  ["H_PilotHelmetHeli_Orange_RF", "reaction forces"],
  ["H_PilotHelmetHeli_Red_RF", "reaction forces"],
  ["H_PilotHelmetHeli_White_RF", "reaction forces"],
  ["H_PilotHelmetHeli_MilGreen_RF", "reaction forces"],
  ["H_PilotHelmetHeli_Yellow_RF", "reaction forces"],
  ["H_HelmetIA_sb_digital_RF", "reaction forces"],
  ["H_HelmetIA_sb_arid_RF", "reaction forces"],
  ["H_HelmetB_plain_sb_geo_RF", "reaction forces"],
  ["H_HelmetB_plain_sb_wdl_RF", "reaction forces"],
  ["H_HelmetB_plain_sb_tna_RF", "reaction forces"],
  ["H_HelmetB_plain_sb_mtp_RF", "reaction forces"],
  ["H_HelmetB_plain_sb_khaki_RF", "reaction forces"],
  ["H_HelmetB_plain_sb_hex_RF", "reaction forces"],
  ["H_HelmetO_ocamo_sb_hex_RF", "reaction forces"],
  ["H_HelmetO_ocamo_sb_urban_RF", "reaction forces"],
  ["H_HelmetAggressor_sb_taiga_RF", "reaction forces"],
  ["H_HelmetHeavy_Black_RF", "reaction forces"],
  ["H_HelmetHeavy_VisorUp_Black_RF", "reaction forces"],
  ["H_HelmetHeavy_Olive_RF", "reaction forces"],
  ["H_HelmetHeavy_VisorUp_Olive_RF", "reaction forces"],
  ["H_HelmetHeavy_White_RF", "reaction forces"],
  ["H_HelmetHeavy_VisorUp_White_RF", "reaction forces"],
  ["H_HelmetHeavy_Sand_RF", "reaction forces"],
  ["H_HelmetHeavy_VisorUp_Sand_RF", "reaction forces"],
  ["H_HelmetHeavy_Hex_RF", "reaction forces"],
  ["H_HelmetHeavy_VisorUp_Hex_RF", "reaction forces"],
  ["H_HelmetHeavy_GHex_RF", "reaction forces"],
  ["H_HelmetHeavy_VisorUp_GHex_RF", "reaction forces"],
  ["H_HelmetHeavy_Simple_Black_RF", "reaction forces"],
  ["H_HelmetHeavy_Simple_Olive_RF", "reaction forces"],
  ["H_HelmetHeavy_Simple_White_RF", "reaction forces"],
  ["H_HelmetHeavy_Simple_Sand_RF", "reaction forces"],
  ["H_HelmetHeavy_Simple_Hex_RF", "reaction forces"],
  ["H_HelmetHeavy_Simple_GHex_RF", "reaction forces"],
  ["H_Helmet_HardHat_Black_RF", "reaction forces"],
  ["H_Helmet_HardHat_Yellow_RF", "reaction forces"],
  ["H_Helmet_HardHat_White_RF", "reaction forces"],
  ["H_Helmet_HardHat_Blue_RF", "reaction forces"],
  ["H_Helmet_HardHat_Orange_RF", "reaction forces"],
  ["H_Helmet_HardHat_Red_RF", "reaction forces"],
  ["H_Helmet_HardHat_Green_RF", "reaction forces"],
  ["H_bmask_snake_lxws", "western sahara"],
  ["H_turban_02_mask_black_lxws", "western sahara"],
  ["H_turban_02_mask_hex_lxws", "western sahara"],
  ["H_turban_02_mask_snake_lxws", "western sahara"],
  ["H_Beret_Headset_lxWS", "western sahara"],
  ["U_B_CTRG_3_lxWS", "western sahara"],
  ["U_B_CTRG_4_lxWS", "western sahara"],
  ["U_lxWS_ION_Casual6", "western sahara"],
  ["U_O_LCF_noInsignia_hex_lxws", "western sahara"],
  ["U_SFIA_deserter_lxWS", "western sahara"],
  ["V_PlateCarrier_CTRG_lxWS", "western sahara"],
  ["U_CBRN_DLC_bluegreen", "contact"],
  ["U_CBRN_DLC_yellow", "contact"],
  ["U_CBRN_DLC_cyan", "contact"],
  ["U_CBRN_DLC_orange", "contact"],
  ["U_C_FormalSuit_01_black_F", "art of war"],
  ["U_C_FormalSuit_01_gray_F", "art of war"],
  ["U_C_FormalSuit_01_blue_F", "art of war"],
  ["U_C_FormalSuit_01_khaki_F", "art of war"],
  ["U_C_FormalSuit_01_tshirt_black_F", "art of war"],
  ["U_C_FormalSuit_01_tshirt_gray_F", "art of war"],
  ["U_B_ParadeUniform_01_US_F", "art of war"],
  ["U_B_ParadeUniform_01_US_decorated_F", "art of war"],
  ["U_O_ParadeUniform_01_CSAT_F", "art of war"],
  ["U_O_ParadeUniform_01_CSAT_decorated_F", "art of war"],
  ["U_I_ParadeUniform_01_AAF_F", "art of war"],
  ["U_I_ParadeUniform_01_AAF_decorated_F", "art of war"],
  ["U_I_E_ParadeUniform_01_LDF_F", "art of war"],
  ["U_I_E_ParadeUniform_01_LDF_decorated_F", "art of war"],
  ["H_ParadeDressCap_01_US_F", "art of war"],
  ["H_ParadeDressCap_01_CSAT_F", "art of war"],
  ["H_ParadeDressCap_01_AAF_F", "art of war"],
  ["H_ParadeDressCap_01_LDF_F", "art of war"],
  ["H_HelmetO_ViperSP_oicamo_F", "apex"],
  ["H_EarProtectors_sand_F", "laws of war"],
  ["H_EarProtectors_olive_F", "laws of war"],
  ["H_HeadSet_sand_F", "laws of war"],
  ["H_HeadSet_olive_F", "laws of war"],
  ["lxWS_H_PASGT_goggles_green_F", "western sahara"],
  ["H_PASGT_goggles_sand_F", "western sahara"],
  ["H_PASGT_basic_green_F", "laws of war"],
  ["H_PASGT_basic_sand_F", "laws of war"],
  ["H_PASGT_basic_UNO_F", "laws of war"],
  ["Aegis_H_PASGT_goggles_UNO_F", "western sahara"],
  ["H_PASGT_neckprot_black_F", "laws of war"],
  ["H_HelmetHBK_olive_F", "contact"],
  ["H_HelmetHBK_olive_headset_F", "contact"],
  ["H_HelmetHBK_olive_ear_F", "contact"],
  ["H_HelmetHBK_olive_chops_F", "contact"],
  ["H_HelmetAggressor_black_F", "contact"],
  ["Aegis_H_HelmetAggressor_cover_ruurban_F", "contact"],
  ["H_HelmetHBK_arid_F", "contact"],
  ["H_HelmetHBK_arid_headset_F", "contact"],
  ["H_HelmetHBK_arid_ear_F", "contact"],
  ["H_HelmetHBK_arid_chops_F", "contact"],
  ["Aegis_lxWS_H_bmask_UwU", "western sahara"],
  ["Aegis_lxWS_H_bmask_AAF", "western sahara"],
  ["Aegis_H_turban_bmask_UwU_lxWS", "western sahara"],
  ["Aegis_H_turban_bmask_ghex_lxWS", "western sahara"],
  ["Aegis_H_turban_bmask_camo01_lxWS", "western sahara"],
  ["Aegis_H_turban_bmask_camo02_lxWS", "western sahara"],
  ["Aegis_H_turban_bmask_white_lxWS", "western sahara"],
  ["Aegis_H_turban_bmask_yellow_lxWS", "western sahara"],
  ["U_B_W_FullGhillie_wdl_F", "marksmen"],
  ["U_B_A_CBRN_Suit_01_MTP_F", "contact"],
  ["Aegis_U_O_LightCombatFatigues_urb_F", "western sahara"],
  ["Aegis_U_O_LightCombatFatigues_ghex_F", "western sahara"],
  ["Aegis_U_O_LightCombatFatigues_dst_F", "western sahara"],
  ["U_I_Uniform_01_tanktop_F", "apex"],
  ["U_C_CBRN_Suit_01_Black_F", "contact"],
  ["U_C_CBRN_Suit_01_Yellow_F", "contact"],
  ["U_B_CTRG_Soldier_Black_F", "apex"],
  ["U_B_CTRG_Soldier_2_Black_F", "apex"],
  ["U_B_CTRG_Soldier_3_Black_F", "apex"],
  ["U_O_V_Soldier_Viper_oicamo_F", "apex"],
  ["U_O_R_FullGhillie_wdl_F", "marksmen"],
  ["Aegis_U_O_LightCombatFatigues_rutaiga_F", "western sahara"],
  ["U_O_R_FullGhillie_ard_F", "marksmen"],
  ["U_O_R_FullGhillie_lsh_F", "marksmen"],
  ["U_O_R_FullGhillie_sard_F", "marksmen"],
  ["Aegis_U_O_LightCombatFatigues_ruarid_F", "western sahara"],
  ["U_I_E_FullGhillie_wdl_F", "marksmen"],
  ["U_I_E_Uniform_01_arid_F", "contact"],
  ["U_I_E_Uniform_01_arid_tanktop_F", "contact"],
  ["U_I_E_Uniform_01_arid_shortsleeve_F", "contact"],
  ["U_I_E_Uniform_01_arid_officer_F", "contact"],
  ["U_B_ION_Uniform_01_poloshirt_wdl_F", "apex"],
  ["U_B_ION_Uniform_01_poloshirt_blue_F", "apex"],
  ["Aegis_U_lxWS_ION_Casual_Hawaiian_F", "western sahara"],
  ["Aegis_U_lxWS_ION_Casual_Hawaiian_2_F", "western sahara"],
  ["Aegis_U_lxWS_ION_Casualtna_F", "western sahara"],
  ["Aegis_U_lxWS_ION_Flanneltna_F", "western sahara"],
  ["Aegis_V_SmershVest_01_blk_F", "contact"],
  ["Aegis_V_SmershVest_01_radio_blk_F", "contact"],
  ["V_HarnessOSpec_blk", "western sahara"],
  ["V_HarnessOSpec_oicamo", "western sahara"],
  ["V_HarnessOSpec_ghex_F", "western sahara"],
  ["V_CarrierRigKBT_01_Black_F", "contact"],
  ["V_CarrierRigKBT_01_light_Black_F", "contact"],
  ["V_CarrierRigKBT_01_heavy_Black_F", "contact"],
  ["V_CarrierRigKBT_01_Coyote_F", "contact"],
  ["V_CarrierRigKBT_01_light_Coyote_F", "contact"],
  ["V_CarrierRigKBT_01_heavy_Coyote_F", "contact"],
  ["V_CarrierRigKBT_01_Khaki_F", "contact"],
  ["V_CarrierRigKBT_01_light_Khaki_F", "contact"],
  ["V_CarrierRigKBT_01_heavy_Khaki_F", "contact"],
  ["V_CarrierRigKBT_01_MTP_F", "contact"],
  ["V_CarrierRigKBT_01_light_MTP_F", "contact"],
  ["V_CarrierRigKBT_01_heavy_MTP_F", "contact"],
  ["Aegis_V_PlateCarrier2_alt_rgr", "western sahara"],
  ["Aegis_V_PlateCarrier2_alt_cbr", "western sahara"],
  ["Aegis_V_PlateCarrier2_alt_khk", "western sahara"],
  ["Aegis_V_PlateCarrier2_alt_mtp", "western sahara"],
  ["Aegis_V_PlateCarrier2_alt_oli", "western sahara"],
  ["Aegis_V_PlateCarrier2_alt_wdl", "western sahara"],
  ["Aegis_V_PlateCarrier2_alt_tna", "western sahara"],
  ["Aegis_V_PlateCarrier2_alt_blk", "western sahara"],
  ["Aegis_V_PlateCarrier2_alt_desert", "western sahara"],
  ["Aegis_U_I_Uniform_01_sweater_02_f", "reaction forces"],
  ["Aegis_V_PlateCarrier_RF_rgr", "reaction forces"],
  ["Aegis_V_PlateCarrier_RF_cbr", "reaction forces"],
  ["Aegis_V_PlateCarrier_RF_khk", "reaction forces"],
  ["Aegis_V_PlateCarrier_RF_mtp", "reaction forces"],
  ["Aegis_V_PlateCarrier_RF_oli", "reaction forces"],
  ["Aegis_V_PlateCarrier_RF_wdl", "reaction forces"],
  ["Aegis_V_PlateCarrier_RF_tna", "reaction forces"],
  ["Aegis_V_PlateCarrier_RF_blk", "reaction forces"],
  ["Aegis_V_PlateCarrier_RF_desert", "reaction forces"],
  ["Aegis_V_TacVest_Rig_gry_RF", "reaction forces"],
  ["Aegis_V_TacVest_Rig_grn_RF", "reaction forces"],
  ["Aegis_V_TacVest_Rig_camo_RF", "reaction forces"],
  ["Aegis_V_TacVest_RigB_khk_RF", "reaction forces"],
  ["Aegis_V_TacVest_RigB_blk_RF", "reaction forces"],
  ["Aegis_V_TacVest_RigB_oli_RF", "reaction forces"],
  ["Aegis_V_TacVest_RigB_gry_RF", "reaction forces"],
  ["Aegis_V_TacVest_RigB_grn_RF", "reaction forces"],
  ["Aegis_V_TacVest_RigB_camo_RF", "reaction forces"],
  ["PLP_UNA_V_Pocketed_F", "laws of war"],
  ["PLP_UNA_V_CarrierRigKBT_01_F", "contact"],
  ["PLP_UNA_V_CarrierRigKBT_01_light_F", "contact"],
  ["PLP_UNA_V_CarrierRigKBT_01_heavy_F", "contact"],
  ["PLP_UNA_V_Plain_F", "laws of war"],
  ["PLP_UNA_V_Safety_F", "laws of war"],
  ["PLP_UNA_H_HelmetHBK_F", "contact"],
  ["PLP_UNA_H_HelmetHBK_headset_F", "contact"],
  ["PLP_UNA_H_HelmetHBK_ear_F", "contact"],
  ["PLP_UNA_H_HelmetHBK_chops_F", "contact"],
  ["PLP_UNA_H_HelmetAggressor_F", "contact"],
  ["PLP_UNA_H_HelmetAggressor_cover_F", "contact"],
  ["PLP_UNA_V_TacVestIR", "western sahara"],
  ["U_O_R_Gorka_01_sage", "contact"],
  ["U_B_Story_ScottAlsworth", "art of war"],
  ["U_C_WorkerCoverallsGloves", "contact"],
  ["U_C_WorkerCoverallsGloves_dgtl", "contact"],
  ["U_C_WorkerCoverallsGloves_grey", "contact"],
  ["U_C_WorkerCoverallsGloves_black", "contact"],
  ["U_C_WorkerCoverallsGloves_orange", "contact"],
  ["H_HelmetHBK_headset_olive", "contact"],
  ["H_HelmetHBK_ear_olive", "contact"],
  ["H_HelmetHBK_chops_olive", "contact"],
  ["H_HelmetHBK_noHeadset", "contact"],
  ["H_Beret_EAF_01_green", "contact"],
  ["V_EOD_olive_dgtl", "laws of war"],
  ["O_NVGoggles_black", "apex"],
  ["O_NVGoggles_blk_F", "apex"],
  ["srifle_DMR_02_tna_F", "marksmen"],
  ["srifle_DMR_05_ghex_F", "marksmen"],
  ["srifle_DMR_06_black_F", "marksmen"],
  ["MMG_01_black_F", "marksmen"],
  ["MMG_01_ghex_F", "marksmen"],
  ["MMG_02_khaki_F", "marksmen"],
  ["Aegis_sgun_AA40_khk_lxWS", "western sahara"],
  ["Aegis_launch_RPG7M_F", "apex"],
  ["LMG_03_khk_F", "apex"],
  ["LMG_03_snd_F", "apex"],
  ["arifle_AK12_545_F", "apex"],
  ["arifle_AK12_545_tan_F", "apex"],
  ["arifle_AK12_545_lush_F", "apex"],
  ["arifle_AK12_545_arid_F", "apex"],
  ["arifle_AK12_GL_545_F", "apex"],
  ["arifle_AK12_GL_545_tan_F", "apex"],
  ["arifle_AK12_GL_545_lush_F", "apex"],
  ["arifle_AK12_GL_545_arid_F", "apex"],
  ["arifle_AK12U_545_F", "contact"],
  ["arifle_AK12U_545_tan_F", "contact"],
  ["arifle_AK12U_545_lush_F", "contact"],
  ["arifle_AK12U_545_arid_F", "contact"],
  ["Aegis_arifle_RPK12_545_F", "contact"],
  ["Aegis_arifle_RPK12_545_tan_F", "contact"],
  ["Aegis_arifle_RPK12_545_lush_F", "contact"],
  ["Aegis_arifle_RPK12_545_arid_F", "contact"],
  ["arifle_AKS_alt_F", "apex"],
  ["arifle_AKSM_F", "apex"],
  ["arifle_AKSM_alt_F", "apex"],
  ["Aegis_arifle_CTAR_tan_f", "apex"],
  ["Aegis_arifle_CTAR_GL_tan_f", "apex"],
  ["Aegis_arifle_CTARS_tan_f", "apex"],
  ["glaunch_GLX_olive_lxWS", "western sahara"],
  ["Aegis_arifle_SPAR_02_inf_blk_F", "apex"],
  ["Aegis_arifle_SPAR_02_inf_khk_F", "apex"],
  ["Aegis_arifle_SPAR_02_inf_snd_F", "apex"],
  ["Aegis_arifle_Velko_oak", "western sahara"],
  ["Aegis_arifle_Velko_sand", "western sahara"],
  ["Aegis_arifle_VelkoR5_oak", "western sahara"],
  ["Aegis_arifle_VelkoR5_sand", "western sahara"],
  ["arifle_NCAR15_F", "apex"],
  ["arifle_NCAR15B_F", "contact"],
  ["arifle_NCAR15_GL_F", "apex"],
  ["arifle_NCAR15_MG_F", "contact"],
  ["ACE_EHP", "laws of war"],
  ["H_HelmetO_ViperSP_whex_F", "apex"],
  ["H_HelmetHBK_aucamo_F", "contact"],
  ["H_HelmetHBK_aucamo_headset_F", "contact"],
  ["H_HelmetHBK_aucamo_ear_F", "contact"],
  ["H_HelmetHBK_aucamo_chops_F", "contact"],
  ["H_HelmetHBK_aucamo_arid_F", "contact"],
  ["H_HelmetHBK_aucamo_arid_headset_F", "contact"],
  ["H_HelmetHBK_aucamo_arid_ear_F", "contact"],
  ["H_HelmetHBK_aucamo_arid_chops_F", "contact"],
  ["H_HelmetHBK_aucamo_tropic_F", "contact"],
  ["H_HelmetHBK_aucamo_tropic_headset_F", "contact"],
  ["H_HelmetHBK_aucamo_tropic_ear_F", "contact"],
  ["H_HelmetHBK_aucamo_tropic_chops_F", "contact"],
  ["H_HelmetHBK_commando_F", "contact"],
  ["H_HelmetHBK_commando_headset_F", "contact"],
  ["H_HelmetHBK_commando_ear_F", "contact"],
  ["Atlas_U_O_V_Soldier_Viper_whex_F", "apex"],
  ["Atlas_U_O_LightCombatFatigues_whex_F", "western sahara"],
  ["Atlas_U_B_G_CombatUniform_wdl", "contact"],
  ["Atlas_U_B_G_CombatUniform_tshirt_wdl", "contact"],
  ["Atlas_U_B_G_CombatUniform_tshirt_arid", "contact"],
  ["Atlas_U_B_G_CombatUniform_vest_wdl", "contact"],
  ["Atlas_U_Tank_wdl_F", "tanks"],
  ["Atlas_U_O_LightCombatFatigues_semiarid_F", "western sahara"],
  ["Atlas_U_B_M_Tank_Marar_F", "tanks"],
  ["Atlas_U_B_M_CBRN_Suit_01_Marar_F", "contact"],
  ["Atlas_U_B_A_CBRN_Suit_01_Aucamo_F", "contact"],
  ["Atlas_U_B_H_Soldier_F", "contact"],
  ["Atlas_U_B_H_Soldier_2_F", "contact"],
  ["Atlas_U_B_H_Soldier_3_F", "apex"],
  ["Atlas_U_B_H_Officer_F", "contact"],
  ["Atlas_U_B_K_CombatUniform", "contact"],
  ["Atlas_U_B_K_CombatUniform_shortsleeve", "western sahara"],
  ["Atlas_U_B_K_CBRN_Suit_01_F", "contact"],
  ["Atlas_U_Tank_olive_F", "tanks"],
  ["Atlas_U_I_I_CBRN_Suit_01_Olive_F", "contact"],
  ["Atlas_U_I_UW_CombatUniform_UNO", "contact"],
  ["Atlas_U_I_UW_CombatUniform_shortsleeve_UNO", "contact"],
  ["Atlas_U_B_JSOC_StealthUniform_F", "apex"],
  ["Atlas_U_B_JSOC_StealthUniform_RolledUp_F", "apex"],
  ["Atlas_U_B_T_JSOC_StealthUniform_F", "apex"],
  ["Atlas_U_B_T_JSOC_StealthUniform_RolledUp_F", "apex"],
  ["Atlas_U_B_W_JSOC_StealthUniform_F", "apex"],
  ["Atlas_U_B_W_JSOC_StealthUniform_RolledUp_F", "apex"],
  ["Atlas_U_B_D_JSOC_StealthUniform_F", "apex"],
  ["Atlas_U_B_D_JSOC_StealthUniform_RolledUp_F", "apex"],
  ["Atlas_U_B_T_JSOC_StealthUniform_alt_F", "apex"],
  ["Atlas_U_B_T_JSOC_StealthUniform_RolledUp_alt_F", "apex"],
  ["V_CarrierRigKBT_01_france_F", "contact"],
  ["V_CarrierRigKBT_01_light_france_F", "contact"],
  ["V_CarrierRigKBT_01_heavy_france_F", "contact"],
  ["V_HarnessOSpec_tan", "western sahara"],
  ["V_HarnessOSpec_whex_F", "western sahara"],
  ["V_SmershVest_01_khaki_F", "contact"],
  ["V_SmershVest_01_radio_khaki_F", "contact"],
  ["V_SmershVest_01_olive_F", "contact"],
  ["V_SmershVest_01_radio_olive_F", "contact"],
  ["V_CarrierRigKBT_01_CDF_F", "contact"],
  ["V_CarrierRigKBT_01_light_CDF_F", "contact"],
  ["V_CarrierRigKBT_01_heavy_CDF_F", "contact"],
  ["Atlas_V_CarrierRigKBT_01_RACS_F", "contact"],
  ["Atlas_V_CarrierRigKBT_01_light_RACS_F", "contact"],
  ["Atlas_V_CarrierRigKBT_01_heavy_RACS_F", "contact"],
  ["Atlas_V_CarrierRigKBT_01_heavy_UNRACS_F", "contact"],
  ["Atlas_V_PlateCarrier2_alt_snd", "western sahara"],
  ["Atlas_V_PlateCarrier2_alt_aucamo", "western sahara"],
  ["Atlas_V_PlateCarrier2_alt_aucamo_ard", "western sahara"],
  ["Atlas_V_PlateCarrier2_alt_aucamo_trp", "western sahara"],
  ["Atlas_V_PlateCarrier_RF_snd", "reaction forces"],
  ["Atlas_V_PlateCarrier_RF_aucamo", "reaction forces"],
  ["Atlas_V_PlateCarrier_RF_aucamo_ard", "reaction forces"],
  ["Atlas_V_PlateCarrier_RF_aucamo_trp", "reaction forces"],
  ["Atlas_V_TacVest_Rig_ard_RF", "reaction forces"],
  ["Atlas_V_TacVest_RigB_ard_RF", "reaction forces"],
  ["Opf_U_O_S_Gorka_01_autumn_F", "contact"],
  ["Opf_U_O_S_Gorka_01_summer_F", "contact"],
  ["Opf_U_I_I_Uniform_01_tshirt_black_F", "apex"],
  ["Opf_U_B_P_Uniform_01_F", "western sahara"],
  ["Opf_U_B_P_Uniform_01_Shortsleeve_F", "contact"],
  ["Opf_U_B_P_FieldJacket_01_F", "apex"],
  ["Opf_U_B_P_FieldJacket_02_F", "apex"],
  ["Opf_U_B_P_FieldJacket_03_F", "apex"],
  ["Opf_U_B_P_Uniform_Advisor_F", "western sahara"],
  ["V_Pocketed_hunter_F", "laws of war"],
  ["V_Pocketed_wdl_F", "laws of war"],
  ["Rev_U_B_BDF_Officer_01_F", "contact"],
  ["Rev_U_B_FRR_Uniform_04_F", "apex"],
  ["Rev_U_B_FRR_Uniform_05_F", "apex"],
  ["Rev_U_B_FRR_Uniform_06_F", "apex"],
  ["Rev_U_B_FRR_Uniform_El_Jefe_F", "contact"],
  ["Rev_U_B_CTRG_Uniform_01_F", "western sahara"],
  ["Rev_U_B_CTRG_Uniform_02_F", "western sahara"],
  ["Rev_U_B_CTRG_Uniform_01_ard_F", "western sahara"],
  ["Rev_U_B_CTRG_Uniform_02_ard_F", "western sahara"],
  ["Rev_U_B_CTRG_Uniform_01_urb_F", "western sahara"],
  ["Rev_U_B_CTRG_Uniform_02_urb_F", "western sahara"],
  ["Rev_V_PlateCarrier2_alt_Cartel", "western sahara"],
  ["V_CarrierRigKBT_01_ctrg_F", "contact"],
  ["V_CarrierRigKBT_01_light_ctrg_F", "contact"],
  ["V_CarrierRigKBT_01_heavy_ctrg_F", "contact"],
  ["G_Combat", "apex"],
  ["G_Glasses_black_RF", "reaction forces"],
  ["G_Glasses_white_RF", "reaction forces"],
  ["G_Balaclava_TI_blk_F", "apex"],
  ["G_Balaclava_TI_tna_F", "apex"],
  ["G_Balaclava_TI_G_blk_F", "apex"],
  ["G_Balaclava_TI_G_tna_F", "apex"],
  ["G_Combat_Goggles_tna_F", "apex"],
  ["G_Respirator_white_F", "laws of war"],
  ["G_Respirator_yellow_F", "laws of war"],
  ["G_Respirator_blue_F", "laws of war"],
  ["G_EyeProtectors_F", "laws of war"],
  ["G_EyeProtectors_Earpiece_F", "laws of war"],
  ["G_WirelessEarpiece_F", "laws of war"],
  ["G_Headset_lxWS", "western sahara"],
  ["G_Combat_lxWS", "western sahara"],
  ["G_AirPurifyingRespirator_01_F", "contact"],
  ["G_AirPurifyingRespirator_01_nofilter_F", "contact"],
  ["G_AirPurifyingRespirator_02_black_F", "contact"],
  ["G_AirPurifyingRespirator_02_black_nofilter_F", "contact"],
  ["G_AirPurifyingRespirator_02_olive_F", "contact"],
  ["G_AirPurifyingRespirator_02_olive_nofilter_F", "contact"],
  ["G_AirPurifyingRespirator_02_sand_F", "contact"],
  ["G_AirPurifyingRespirator_02_sand_nofilter_F", "contact"],
  ["G_RegulatorMask_F", "contact"],
  ["G_Blindfold_01_white_F", "contact"],
  ["G_Blindfold_01_black_F", "contact"],
  ["G_Balaclava_TI_alt_F", "apex"],
  ["G_Balaclava_TI_G_alt_F", "apex"],
  ["G_Combat_Goggles_blk_F", "apex"],
  ["G_Balaclava_light_blk_F", "apex"],
  ["G_Balaclava_light_mtp_F", "apex"],
  ["G_Balaclava_light_tropic_F", "apex"],
  ["G_Balaclava_light_eaf_F", "apex"],
  ["G_Balaclava_light_wdl_F", "apex"],
  ["G_Balaclava_light_G_blk_F", "apex"],
  ["G_Balaclava_light_G_mtp_F", "apex"],
  ["G_Balaclava_light_G_tropic_F", "apex"],
  ["G_Balaclava_light_G_eaf_F", "apex"],
  ["G_Balaclava_light_G_wdl_F", "apex"],
  ["Aegis_G_Headset_black_F", "laws of war"],
  ["Aegis_G_Headset_red_F", "laws of war"],
  ["Aegis_G_Headset_orange_F", "laws of war"],
  ["Aegis_G_Headset_white_F", "laws of war"],
  ["Aegis_G_Headset_Yellow_F", "laws of war"],
  ["Aegis_G_Headset_Olive_F", "laws of war"],
  ["Aegis_G_Headset_Sand_F", "laws of war"],
  ["B_shield_backpack_lxWS", "western sahara"],
  ["I_shield_backpack_lxWS", "western sahara"],
  ["O_shield_backpack_lxWS", "western sahara"],
  ["O_shield_backpack_GHEX_lxWS", "western sahara"],
  ["EF_B_RaiderPack_coy", "expeditionary forces"],
  ["EF_B_RaiderPack_olive", "expeditionary forces"],
  ["EF_B_RaiderPack_black", "expeditionary forces"],
  ["B_DuffleBag_Black_RF", "reaction forces"],
  ["B_DuffleBag_MTP_RF", "reaction forces"],
  ["B_DuffleBag_Olive_RF", "reaction forces"],
  ["B_DuffleBag_Red_RF", "reaction forces"],
  ["B_DuffleBag_Blue_RF", "reaction forces"],
  ["B_DuffleBag_Sand_RF", "reaction forces"],
  ["B_DuffleBag_VRANA_RF", "reaction forces"],
  ["B_DuffleBag_Black_NoLogo_RF", "reaction forces"],
  ["B_DuffleBag_Olive_NoLogo_RF", "reaction forces"],
  ["B_DuffleBag_Sand_NoLogo_RF", "reaction forces"],
  ["C_Parachute_Orange_RF", "reaction forces"],
  ["C_Parachute_White_RF", "reaction forces"],
  ["C_Parachute_Green_RF", "reaction forces"],
  ["C_Parachute_Blue_RF", "reaction forces"],
  ["C_Parachute_Yellow_RF", "reaction forces"],
  ["B_Static_Designator_01_weapon_F", "marksmen"],
  ["O_Static_Designator_02_weapon_F", "marksmen"],
  ["B_ViperHarness_blk_F", "apex"],
  ["B_ViperHarness_ghex_F", "apex"],
  ["B_ViperHarness_hex_F", "apex"],
  ["B_ViperHarness_khk_F", "apex"],
  ["B_ViperHarness_oli_F", "apex"],
  ["B_ViperLightHarness_blk_F", "apex"],
  ["B_ViperLightHarness_ghex_F", "apex"],
  ["B_ViperLightHarness_hex_F", "apex"],
  ["B_ViperLightHarness_khk_F", "apex"],
  ["B_ViperLightHarness_oli_F", "apex"],
  ["B_CommandoMortar_weapon_RF", "reaction forces"],
  ["O_CommandoMortar_weapon_RF", "reaction forces"],
  ["I_CommandoMortar_weapon_RF", "reaction forces"],
  ["I_E_CommandoMortar_weapon_RF", "reaction forces"],
  ["EF_B_CommandoMortar_weapon_MJTF_Des", "reaction forces"],
  ["EF_B_CommandoMortar_weapon_MJTF_Wdl", "reaction forces"],
  ["B_SCBA_01_F", "contact"],
  ["CBRN_Division_CBRN_Specialist_pack", "contact"],
  ["CBRN_Division_CBRN_Security_pack", "contact"],
  ["B_UAV_02_backpack_lxWS", "western sahara"],
  ["ION_UAV_02_backpack_lxWS", "western sahara"],
  ["I_UAV_02_backpack_lxWS", "western sahara"],
  ["O_UAV_02_backpack_lxWS", "western sahara"],
  ["B_Tura_UAV_02_IED_backpack_lxWS", "western sahara"],
  ["B_G_UAV_02_IED_backpack_lxWS", "western sahara"],
  ["B_Messenger_Coyote_F", "laws of war"],
  ["B_Messenger_Olive_F", "laws of war"],
  ["B_Messenger_Black_F", "laws of war"],
  ["B_Messenger_Gray_F", "laws of war"],
  ["B_Messenger_IDAP_F", "laws of war"],
  ["B_UAV_06_backpack_F", "laws of war"],
  ["O_UAV_06_backpack_F", "laws of war"],
  ["I_UAV_06_backpack_F", "laws of war"],
  ["C_IDAP_UAV_06_backpack_F", "laws of war"],
  ["C_UAV_06_backpack_F", "laws of war"],
  ["C_IDAP_UAV_06_antimine_backpack_F", "laws of war"],
  ["B_UAV_06_medical_backpack_F", "laws of war"],
  ["O_UAV_06_medical_backpack_F", "laws of war"],
  ["I_UAV_06_medical_backpack_F", "laws of war"],
  ["C_IDAP_UAV_06_medical_backpack_F", "laws of war"],
  ["C_UAV_06_medical_backpack_F", "laws of war"],
  ["B_LegStrapBag_black_F", "laws of war"],
  ["B_LegStrapBag_coyote_F", "laws of war"],
  ["B_LegStrapBag_olive_F", "laws of war"],
  ["CBRN_CBRN_Specialist_pack", "contact"],
  ["CBRN_CBRN_Specialist_Hazardous_pack", "contact"],
  ["B_W_Static_Designator_01_weapon_F", "marksmen"],
  ["B_CombinationUnitRespirator_01_F", "contact"],
  ["B_UGV_02_Science_backpack_F", "contact"],
  ["B_UGV_02_Demining_backpack_F", "contact"],
  ["O_UGV_02_Science_backpack_F", "contact"],
  ["O_UGV_02_Demining_backpack_F", "contact"],
  ["I_UGV_02_Science_backpack_F", "contact"],
  ["I_E_UGV_02_Science_backpack_F", "contact"],
  ["I_UGV_02_Demining_backpack_F", "contact"],
  ["I_E_UGV_02_Demining_backpack_F", "contact"],
  ["C_IDAP_UGV_02_Demining_backpack_F", "contact"],
  ["I_E_UAV_06_backpack_F", "laws of war"],
  ["I_E_UAV_06_medical_backpack_F", "laws of war"],
  ["B_RadioBag_01_wdl_F", "contact"],
  ["B_RadioBag_01_mtp_F", "contact"],
  ["B_RadioBag_01_tropic_F", "contact"],
  ["B_RadioBag_01_black_F", "contact"],
  ["B_RadioBag_01_hex_F", "contact"],
  ["B_RadioBag_01_oucamo_F", "contact"],
  ["B_RadioBag_01_ghex_F", "contact"],
  ["B_RadioBag_01_digi_F", "contact"],
  ["B_RadioBag_01_eaf_F", "contact"],
  ["B_CivilianBackpack_01_Sport_Blue_F", "art of war"],
  ["B_CivilianBackpack_01_Sport_Red_F", "art of war"],
  ["B_CivilianBackpack_01_Sport_Green_F", "art of war"],
  ["B_CivilianBackpack_01_Everyday_Black_F", "art of war"],
  ["B_CivilianBackpack_01_Everyday_Vrana_F", "art of war"],
  ["B_CivilianBackpack_01_Everyday_Astra_F", "art of war"],
  ["B_CivilianBackpack_01_Everyday_IDAP_F", "art of war"],
  ["O_R_UGV_02_Demining_backpack_F", "contact"],
  ["B_T_Static_Designator_01_Weapon_F", "marksmen"],
  ["I_Static_Designator_01_weapon_F", "marksmen"],
  ["I_E_Static_Designator_01_weapon_F", "marksmen"],
  ["O_T_Static_Designator_02_weapon_F", "marksmen"],
  ["O_R_Static_Designator_02_weapon_F", "marksmen"],
  ["B_ViperHarness_oicamo_F", "apex"],
  ["B_ViperLightHarness_oicamo_F", "apex"],
  ["B_RadioBag_01_coyote_F", "contact"],
  ["B_RadioBag_01_sage_F", "contact"],
  ["B_RadioBag_01_green_F", "contact"],
  ["B_RadioBag_01_taiga_F", "contact"],
  ["B_RadioBag_01_arid_F", "contact"],
  ["B_RadioBag_01_oicamo_F", "contact"],
  ["Aegis_B_RadioBag_01_des_lxWS", "contact"],
  ["B_D_CTRG_CommandoMortar_weapon_RF", "reaction forces"],
  ["Aegis_B_A_UAV_02_backpack_lxWS", "western sahara"],
  ["Aegis_B_CTRG_UAV_02_backpack_lxWS", "western sahara"],
  ["Aegis_O_R_UAV_02_backpack_lxWS", "western sahara"],
  ["Aegis_I_Raven_UAV_02_backpack_lxWS", "western sahara"],
  ["Aegis_I_E_UAV_02_backpack_lxWS", "western sahara"],
  ["Aegis_B_E_UAV_02_backpack_lxWS", "western sahara"],
  ["O_R_UAV_06_backpack_F", "laws of war"],
  ["O_R_UAV_06_medical_backpack_F", "laws of war"],
  ["I_Raven_UAV_06_backpack_F", "laws of war"],
  ["I_Raven_UAV_06_medical_backpack_F", "laws of war"],
  ["dcx_shield_backpack_bluhex", "western sahara"],
  ["dcx_shield_backpack_ctrg", "western sahara"],
  ["dcx_shield_backpack_ctrg_temperate", "western sahara"],
  ["dcx_shield_backpack_ldf", "western sahara"],
  ["dcx_shield_backpack_una", "western sahara"],
  ["dcx_shield_backpack_snd", "western sahara"],
  ["dcx_shield_backpack_oli", "western sahara"],
  ["dcx_shield_backpack_gen", "western sahara"],
  ["B_SCBA_01_noPop_respirator", "contact"],
  ["B_SCBA_01_noPop_regulator", "contact"],
  ["B_CombinationUnitRespirator_01_noPop_respirator", "contact"],
  ["B_CombinationUnitRespirator_01_noPop_regulator", "contact"],
  ["dcx_spetsnaz_cmort_weapon", "reaction forces"],
  ["Atlas_I_I_UGV_02_Demining_backpack_F", "contact"],
  ["Atlas_I_UNO_UGV_02_Demining_backpack_F", "contact"],
  ["Atlas_I_I_Static_Designator_01_weapon_F", "marksmen"],
  ["B_RadioBag_01_aucamo_F", "contact"],
  ["B_RadioBag_01_whex_F", "contact"],
  ["B_RadioBag_01_flecktarn_F", "contact"],
  ["B_RadioBag_01_multitarn_F", "contact"],
  ["B_RadioBag_01_semiarid_F", "contact"],
  ["B_RadioBag_01_jungle_F", "contact"],
  ["B_RadioBag_01_marar_F", "contact"],
  ["B_RadioBag_01_commando_F", "contact"],
  ["B_RadioBag_01_kzg_F", "contact"],
  ["B_RadioBag_01_ardi_F", "contact"],
  ["B_ViperHarness_whex_F", "apex"],
  ["B_ViperLightHarness_whex_F", "apex"],
  ["B_RadioBag_01_m81_F", "contact"],
  ["B_RadioBag_01_vhex_F", "contact"],
  ["Atlas_B_A_UAV_02_backpack_lxWS", "western sahara"],
  ["Atlas_I_I_UAV_02_backpack_lxWS", "western sahara"],
  ["Atlas_B_A_UAV_06_backpack_F", "laws of war"],
  ["Atlas_B_A_UAV_06_medical_backpack_F", "laws of war"],
  ["Atlas_I_I_UAV_06_backpack_F", "laws of war"],
  ["Atlas_I_I_UAV_06_medical_backpack_F", "laws of war"],
  ["Atlas_I_UNO_UAV_06_backpack_F", "laws of war"],
  ["Atlas_I_UNO_UAV_06_medical_backpack_F", "laws of war"]
];
