remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Jamio's Mission Framework
description: This is a very basic, janky mission framework for use with my Arma 3 unit.
show_downloads: true
